// Code generated by protoc-gen-go.
// source: battle.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NodeBatchInfo_ struct {
	Step             *int32             `protobuf:"varint,1,opt,name=Step" json:"Step,omitempty"`
	Monsters         []*BattleHeroInfo_ `protobuf:"bytes,2,rep,name=Monsters" json:"Monsters,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *NodeBatchInfo_) Reset()                    { *m = NodeBatchInfo_{} }
func (m *NodeBatchInfo_) String() string            { return proto.CompactTextString(m) }
func (*NodeBatchInfo_) ProtoMessage()               {}
func (*NodeBatchInfo_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *NodeBatchInfo_) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *NodeBatchInfo_) GetMonsters() []*BattleHeroInfo_ {
	if m != nil {
		return m.Monsters
	}
	return nil
}

type NodeInfo_ struct {
	Idx              *int32            `protobuf:"varint,1,opt,name=Idx" json:"Idx,omitempty"`
	Vit              *int32            `protobuf:"varint,2,opt,name=Vit" json:"Vit,omitempty"`
	KeyCost          *int32            `protobuf:"varint,3,opt,name=KeyCost" json:"KeyCost,omitempty"`
	KeyGet           *int32            `protobuf:"varint,4,opt,name=KeyGet" json:"KeyGet,omitempty"`
	Rewards          []*Reward_Info_   `protobuf:"bytes,5,rep,name=Rewards" json:"Rewards,omitempty"`
	PickRewards      []*Reward_Info_   `protobuf:"bytes,6,rep,name=PickRewards" json:"PickRewards,omitempty"`
	MonsterBatch     []*NodeBatchInfo_ `protobuf:"bytes,7,rep,name=MonsterBatch" json:"MonsterBatch,omitempty"`
	AdventureID      []int32           `protobuf:"varint,8,rep,name=AdventureID" json:"AdventureID,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NodeInfo_) Reset()                    { *m = NodeInfo_{} }
func (m *NodeInfo_) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo_) ProtoMessage()               {}
func (*NodeInfo_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *NodeInfo_) GetIdx() int32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *NodeInfo_) GetVit() int32 {
	if m != nil && m.Vit != nil {
		return *m.Vit
	}
	return 0
}

func (m *NodeInfo_) GetKeyCost() int32 {
	if m != nil && m.KeyCost != nil {
		return *m.KeyCost
	}
	return 0
}

func (m *NodeInfo_) GetKeyGet() int32 {
	if m != nil && m.KeyGet != nil {
		return *m.KeyGet
	}
	return 0
}

func (m *NodeInfo_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *NodeInfo_) GetPickRewards() []*Reward_Info_ {
	if m != nil {
		return m.PickRewards
	}
	return nil
}

func (m *NodeInfo_) GetMonsterBatch() []*NodeBatchInfo_ {
	if m != nil {
		return m.MonsterBatch
	}
	return nil
}

func (m *NodeInfo_) GetAdventureID() []int32 {
	if m != nil {
		return m.AdventureID
	}
	return nil
}

type ChapterInfo_ struct {
	ID               *int32       `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	TableInfo        *TableInfo_  `protobuf:"bytes,2,opt,name=TableInfo" json:"TableInfo,omitempty"`
	NodeInfo         []*NodeInfo_ `protobuf:"bytes,3,rep,name=NodeInfo" json:"NodeInfo,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ChapterInfo_) Reset()                    { *m = ChapterInfo_{} }
func (m *ChapterInfo_) String() string            { return proto.CompactTextString(m) }
func (*ChapterInfo_) ProtoMessage()               {}
func (*ChapterInfo_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *ChapterInfo_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *ChapterInfo_) GetTableInfo() *TableInfo_ {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

func (m *ChapterInfo_) GetNodeInfo() []*NodeInfo_ {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

// //////////////////////////////  消息结构体 ////////////////////////////////////
type Req_ChapterInfo_ struct {
	ID               []int32 `protobuf:"varint,1,rep,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_ChapterInfo_) Reset()                    { *m = Req_ChapterInfo_{} }
func (m *Req_ChapterInfo_) String() string            { return proto.CompactTextString(m) }
func (*Req_ChapterInfo_) ProtoMessage()               {}
func (*Req_ChapterInfo_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *Req_ChapterInfo_) GetID() []int32 {
	if m != nil {
		return m.ID
	}
	return nil
}

type Resp_ChapterInfo_ struct {
	ChapterInfo      []*ChapterInfo_ `protobuf:"bytes,1,rep,name=ChapterInfo" json:"ChapterInfo,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_ChapterInfo_) Reset()                    { *m = Resp_ChapterInfo_{} }
func (m *Resp_ChapterInfo_) String() string            { return proto.CompactTextString(m) }
func (*Resp_ChapterInfo_) ProtoMessage()               {}
func (*Resp_ChapterInfo_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *Resp_ChapterInfo_) GetChapterInfo() []*ChapterInfo_ {
	if m != nil {
		return m.ChapterInfo
	}
	return nil
}

// 推送 沙盘数据更新（替换阵容后的push）
type Push_Table_Update_ struct {
	ChapterInfo      []*ChapterInfo_ `protobuf:"bytes,1,rep,name=ChapterInfo" json:"ChapterInfo,omitempty"`
	MineTableInfo    *TableInfo_     `protobuf:"bytes,2,opt,name=MineTableInfo" json:"MineTableInfo,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Push_Table_Update_) Reset()                    { *m = Push_Table_Update_{} }
func (m *Push_Table_Update_) String() string            { return proto.CompactTextString(m) }
func (*Push_Table_Update_) ProtoMessage()               {}
func (*Push_Table_Update_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *Push_Table_Update_) GetChapterInfo() []*ChapterInfo_ {
	if m != nil {
		return m.ChapterInfo
	}
	return nil
}

func (m *Push_Table_Update_) GetMineTableInfo() *TableInfo_ {
	if m != nil {
		return m.MineTableInfo
	}
	return nil
}

type Req_ChapterNode_PickUp_ struct {
	ID               *int32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	NodeID           *int32 `protobuf:"varint,2,opt,name=NodeID" json:"NodeID,omitempty"`
	PickRewardIdx    *int32 `protobuf:"varint,3,opt,name=PickRewardIdx" json:"PickRewardIdx,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_ChapterNode_PickUp_) Reset()                    { *m = Req_ChapterNode_PickUp_{} }
func (m *Req_ChapterNode_PickUp_) String() string            { return proto.CompactTextString(m) }
func (*Req_ChapterNode_PickUp_) ProtoMessage()               {}
func (*Req_ChapterNode_PickUp_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *Req_ChapterNode_PickUp_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Req_ChapterNode_PickUp_) GetNodeID() int32 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

func (m *Req_ChapterNode_PickUp_) GetPickRewardIdx() int32 {
	if m != nil && m.PickRewardIdx != nil {
		return *m.PickRewardIdx
	}
	return 0
}

type Resp_ChapterNode_PickUp_ struct {
	ID               *int32        `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	NodeID           *int32        `protobuf:"varint,2,opt,name=NodeID" json:"NodeID,omitempty"`
	Reward           *Reward_Info_ `protobuf:"bytes,3,opt,name=Reward" json:"Reward,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Resp_ChapterNode_PickUp_) Reset()                    { *m = Resp_ChapterNode_PickUp_{} }
func (m *Resp_ChapterNode_PickUp_) String() string            { return proto.CompactTextString(m) }
func (*Resp_ChapterNode_PickUp_) ProtoMessage()               {}
func (*Resp_ChapterNode_PickUp_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *Resp_ChapterNode_PickUp_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Resp_ChapterNode_PickUp_) GetNodeID() int32 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

func (m *Resp_ChapterNode_PickUp_) GetReward() *Reward_Info_ {
	if m != nil {
		return m.Reward
	}
	return nil
}

type Req_ChapterBattleSet_ struct {
	ID               *int32             `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	TableInfo        *TableInfo_        `protobuf:"bytes,2,opt,name=TableInfo" json:"TableInfo,omitempty"`
	NodeInfos        []*BattleNodeInfo_ `protobuf:"bytes,3,rep,name=NodeInfos" json:"NodeInfos,omitempty"`
	HeroInfos        []*BattleHeroInfo_ `protobuf:"bytes,4,rep,name=HeroInfos" json:"HeroInfos,omitempty"`
	NodeID           *int32             `protobuf:"varint,5,opt,name=NodeID" json:"NodeID,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Req_ChapterBattleSet_) Reset()                    { *m = Req_ChapterBattleSet_{} }
func (m *Req_ChapterBattleSet_) String() string            { return proto.CompactTextString(m) }
func (*Req_ChapterBattleSet_) ProtoMessage()               {}
func (*Req_ChapterBattleSet_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *Req_ChapterBattleSet_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Req_ChapterBattleSet_) GetTableInfo() *TableInfo_ {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

func (m *Req_ChapterBattleSet_) GetNodeInfos() []*BattleNodeInfo_ {
	if m != nil {
		return m.NodeInfos
	}
	return nil
}

func (m *Req_ChapterBattleSet_) GetHeroInfos() []*BattleHeroInfo_ {
	if m != nil {
		return m.HeroInfos
	}
	return nil
}

func (m *Req_ChapterBattleSet_) GetNodeID() int32 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

type Resp_ChapterBattleSet_ struct {
	ExtraID          *int32 `protobuf:"varint,1,opt,name=ExtraID" json:"ExtraID,omitempty"`
	Share            *int32 `protobuf:"varint,2,opt,name=Share" json:"Share,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_ChapterBattleSet_) Reset()                    { *m = Resp_ChapterBattleSet_{} }
func (m *Resp_ChapterBattleSet_) String() string            { return proto.CompactTextString(m) }
func (*Resp_ChapterBattleSet_) ProtoMessage()               {}
func (*Resp_ChapterBattleSet_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *Resp_ChapterBattleSet_) GetExtraID() int32 {
	if m != nil && m.ExtraID != nil {
		return *m.ExtraID
	}
	return 0
}

func (m *Resp_ChapterBattleSet_) GetShare() int32 {
	if m != nil && m.Share != nil {
		return *m.Share
	}
	return 0
}

type Req_ChapterBattleReset_ struct {
	ID               *int32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_ChapterBattleReset_) Reset()                    { *m = Req_ChapterBattleReset_{} }
func (m *Req_ChapterBattleReset_) String() string            { return proto.CompactTextString(m) }
func (*Req_ChapterBattleReset_) ProtoMessage()               {}
func (*Req_ChapterBattleReset_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *Req_ChapterBattleReset_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

type Resp_ChapterBattleReset_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_ChapterBattleReset_) Reset()                    { *m = Resp_ChapterBattleReset_{} }
func (m *Resp_ChapterBattleReset_) String() string            { return proto.CompactTextString(m) }
func (*Resp_ChapterBattleReset_) ProtoMessage()               {}
func (*Resp_ChapterBattleReset_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

type Req_ChapterNodeState_ struct {
	ID               *int32        `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	NodeID           *int32        `protobuf:"varint,2,opt,name=NodeID" json:"NodeID,omitempty"`
	State            *int32        `protobuf:"varint,3,opt,name=State" json:"State,omitempty"`
	Reels            []*Reel_Info_ `protobuf:"bytes,4,rep,name=Reels" json:"Reels,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Req_ChapterNodeState_) Reset()                    { *m = Req_ChapterNodeState_{} }
func (m *Req_ChapterNodeState_) String() string            { return proto.CompactTextString(m) }
func (*Req_ChapterNodeState_) ProtoMessage()               {}
func (*Req_ChapterNodeState_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

func (m *Req_ChapterNodeState_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Req_ChapterNodeState_) GetNodeID() int32 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

func (m *Req_ChapterNodeState_) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *Req_ChapterNodeState_) GetReels() []*Reel_Info_ {
	if m != nil {
		return m.Reels
	}
	return nil
}

type Resp_ChapterNodeState_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_ChapterNodeState_) Reset()                    { *m = Resp_ChapterNodeState_{} }
func (m *Resp_ChapterNodeState_) String() string            { return proto.CompactTextString(m) }
func (*Resp_ChapterNodeState_) ProtoMessage()               {}
func (*Resp_ChapterNodeState_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{13} }

type Req_ChapterState_ struct {
	ID               *int32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	State            *int32 `protobuf:"varint,2,opt,name=State" json:"State,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_ChapterState_) Reset()                    { *m = Req_ChapterState_{} }
func (m *Req_ChapterState_) String() string            { return proto.CompactTextString(m) }
func (*Req_ChapterState_) ProtoMessage()               {}
func (*Req_ChapterState_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{14} }

func (m *Req_ChapterState_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Req_ChapterState_) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

type Resp_ChapterState_ struct {
	ID               *int32       `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	State            *int32       `protobuf:"varint,2,opt,name=State" json:"State,omitempty"`
	ChestInfo        *Chest_Info_ `protobuf:"bytes,3,opt,name=ChestInfo" json:"ChestInfo,omitempty"`
	MopUpVit         *int32       `protobuf:"varint,4,opt,name=MopUpVit" json:"MopUpVit,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Resp_ChapterState_) Reset()                    { *m = Resp_ChapterState_{} }
func (m *Resp_ChapterState_) String() string            { return proto.CompactTextString(m) }
func (*Resp_ChapterState_) ProtoMessage()               {}
func (*Resp_ChapterState_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{15} }

func (m *Resp_ChapterState_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Resp_ChapterState_) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *Resp_ChapterState_) GetChestInfo() *Chest_Info_ {
	if m != nil {
		return m.ChestInfo
	}
	return nil
}

func (m *Resp_ChapterState_) GetMopUpVit() int32 {
	if m != nil && m.MopUpVit != nil {
		return *m.MopUpVit
	}
	return 0
}

type Req_ChapterMopUp_ struct {
	ID               *int32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_ChapterMopUp_) Reset()                    { *m = Req_ChapterMopUp_{} }
func (m *Req_ChapterMopUp_) String() string            { return proto.CompactTextString(m) }
func (*Req_ChapterMopUp_) ProtoMessage()               {}
func (*Req_ChapterMopUp_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{16} }

func (m *Req_ChapterMopUp_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

type Resp_ChapterMopUp_ struct {
	ChestInfo        *Chest_Info_ `protobuf:"bytes,1,opt,name=ChestInfo" json:"ChestInfo,omitempty"`
	Vit              *int32       `protobuf:"varint,2,opt,name=Vit" json:"Vit,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Resp_ChapterMopUp_) Reset()                    { *m = Resp_ChapterMopUp_{} }
func (m *Resp_ChapterMopUp_) String() string            { return proto.CompactTextString(m) }
func (*Resp_ChapterMopUp_) ProtoMessage()               {}
func (*Resp_ChapterMopUp_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{17} }

func (m *Resp_ChapterMopUp_) GetChestInfo() *Chest_Info_ {
	if m != nil {
		return m.ChestInfo
	}
	return nil
}

func (m *Resp_ChapterMopUp_) GetVit() int32 {
	if m != nil && m.Vit != nil {
		return *m.Vit
	}
	return 0
}

// 奇遇选择
type Req_Adventure_Choose_ struct {
	ID               *int32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	NodeID           *int32 `protobuf:"varint,2,opt,name=NodeID" json:"NodeID,omitempty"`
	AdventureID      *int32 `protobuf:"varint,3,opt,name=AdventureID" json:"AdventureID,omitempty"`
	ChooseIdx        *int32 `protobuf:"varint,4,opt,name=ChooseIdx" json:"ChooseIdx,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Adventure_Choose_) Reset()                    { *m = Req_Adventure_Choose_{} }
func (m *Req_Adventure_Choose_) String() string            { return proto.CompactTextString(m) }
func (*Req_Adventure_Choose_) ProtoMessage()               {}
func (*Req_Adventure_Choose_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{18} }

func (m *Req_Adventure_Choose_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Req_Adventure_Choose_) GetNodeID() int32 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

func (m *Req_Adventure_Choose_) GetAdventureID() int32 {
	if m != nil && m.AdventureID != nil {
		return *m.AdventureID
	}
	return 0
}

func (m *Req_Adventure_Choose_) GetChooseIdx() int32 {
	if m != nil && m.ChooseIdx != nil {
		return *m.ChooseIdx
	}
	return 0
}

// 奇遇响应
type Resp_Adventure_Choose_ struct {
	Rewards          []*Reward_Info_ `protobuf:"bytes,1,rep,name=Rewards" json:"Rewards,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Adventure_Choose_) Reset()                    { *m = Resp_Adventure_Choose_{} }
func (m *Resp_Adventure_Choose_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Adventure_Choose_) ProtoMessage()               {}
func (*Resp_Adventure_Choose_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{19} }

func (m *Resp_Adventure_Choose_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

// 请求 神秘商店
type Req_MysticStore_ struct {
	ID               *int32 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	NodeID           *int32 `protobuf:"varint,2,opt,name=NodeID" json:"NodeID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_MysticStore_) Reset()                    { *m = Req_MysticStore_{} }
func (m *Req_MysticStore_) String() string            { return proto.CompactTextString(m) }
func (*Req_MysticStore_) ProtoMessage()               {}
func (*Req_MysticStore_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{20} }

func (m *Req_MysticStore_) GetID() int32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Req_MysticStore_) GetNodeID() int32 {
	if m != nil && m.NodeID != nil {
		return *m.NodeID
	}
	return 0
}

// 响应 神秘商店
type Resp_MysticStore_ struct {
	GoodsID          []int32         `protobuf:"varint,1,rep,name=GoodsID" json:"GoodsID,omitempty"`
	Goods            []*Reward_Info_ `protobuf:"bytes,2,rep,name=Goods" json:"Goods,omitempty"`
	Price            []*Reward_Info_ `protobuf:"bytes,3,rep,name=Price" json:"Price,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_MysticStore_) Reset()                    { *m = Resp_MysticStore_{} }
func (m *Resp_MysticStore_) String() string            { return proto.CompactTextString(m) }
func (*Resp_MysticStore_) ProtoMessage()               {}
func (*Resp_MysticStore_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{21} }

func (m *Resp_MysticStore_) GetGoodsID() []int32 {
	if m != nil {
		return m.GoodsID
	}
	return nil
}

func (m *Resp_MysticStore_) GetGoods() []*Reward_Info_ {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *Resp_MysticStore_) GetPrice() []*Reward_Info_ {
	if m != nil {
		return m.Price
	}
	return nil
}

// 请求 购买神秘商店物品
type Req_Buy_MysticStore_ struct {
	GoodsID          *int32 `protobuf:"varint,1,opt,name=GoodsID" json:"GoodsID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Buy_MysticStore_) Reset()                    { *m = Req_Buy_MysticStore_{} }
func (m *Req_Buy_MysticStore_) String() string            { return proto.CompactTextString(m) }
func (*Req_Buy_MysticStore_) ProtoMessage()               {}
func (*Req_Buy_MysticStore_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{22} }

func (m *Req_Buy_MysticStore_) GetGoodsID() int32 {
	if m != nil && m.GoodsID != nil {
		return *m.GoodsID
	}
	return 0
}

// 响应 购买神秘商品物品
type Resp_Buy_MysticStore_ struct {
	Goods            *Reward_Info_ `protobuf:"bytes,1,opt,name=Goods" json:"Goods,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Resp_Buy_MysticStore_) Reset()                    { *m = Resp_Buy_MysticStore_{} }
func (m *Resp_Buy_MysticStore_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Buy_MysticStore_) ProtoMessage()               {}
func (*Resp_Buy_MysticStore_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{23} }

func (m *Resp_Buy_MysticStore_) GetGoods() *Reward_Info_ {
	if m != nil {
		return m.Goods
	}
	return nil
}

// 请求 离开神秘商店
type Req_Leave_MysticStore_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Leave_MysticStore_) Reset()                    { *m = Req_Leave_MysticStore_{} }
func (m *Req_Leave_MysticStore_) String() string            { return proto.CompactTextString(m) }
func (*Req_Leave_MysticStore_) ProtoMessage()               {}
func (*Req_Leave_MysticStore_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{24} }

// 请求 祭坛
type Req_Altar_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Altar_) Reset()                    { *m = Req_Altar_{} }
func (m *Req_Altar_) String() string            { return proto.CompactTextString(m) }
func (*Req_Altar_) ProtoMessage()               {}
func (*Req_Altar_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{25} }

// 响应 祭坛
type Resp_Altar_ struct {
	Goods            []*Reward_Info_ `protobuf:"bytes,1,rep,name=Goods" json:"Goods,omitempty"`
	Price            *Reward_Info_   `protobuf:"bytes,2,opt,name=Price" json:"Price,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Altar_) Reset()                    { *m = Resp_Altar_{} }
func (m *Resp_Altar_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Altar_) ProtoMessage()               {}
func (*Resp_Altar_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{26} }

func (m *Resp_Altar_) GetGoods() []*Reward_Info_ {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *Resp_Altar_) GetPrice() *Reward_Info_ {
	if m != nil {
		return m.Price
	}
	return nil
}

// 请求 购买祭坛
type Req_Buy_Altar_ struct {
	Goods            []*Reward_Info_ `protobuf:"bytes,1,rep,name=Goods" json:"Goods,omitempty"`
	Price            *Reward_Info_   `protobuf:"bytes,2,opt,name=Price" json:"Price,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Req_Buy_Altar_) Reset()                    { *m = Req_Buy_Altar_{} }
func (m *Req_Buy_Altar_) String() string            { return proto.CompactTextString(m) }
func (*Req_Buy_Altar_) ProtoMessage()               {}
func (*Req_Buy_Altar_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{27} }

func (m *Req_Buy_Altar_) GetGoods() []*Reward_Info_ {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *Req_Buy_Altar_) GetPrice() *Reward_Info_ {
	if m != nil {
		return m.Price
	}
	return nil
}

// 响应 购买祭坛
type Resp_Buy_Altar_ struct {
	Goods            []*Reward_Info_ `protobuf:"bytes,1,rep,name=Goods" json:"Goods,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Buy_Altar_) Reset()                    { *m = Resp_Buy_Altar_{} }
func (m *Resp_Buy_Altar_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Buy_Altar_) ProtoMessage()               {}
func (*Resp_Buy_Altar_) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{28} }

func (m *Resp_Buy_Altar_) GetGoods() []*Reward_Info_ {
	if m != nil {
		return m.Goods
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeBatchInfo_)(nil), "protocol.NodeBatchInfo_")
	proto.RegisterType((*NodeInfo_)(nil), "protocol.NodeInfo_")
	proto.RegisterType((*ChapterInfo_)(nil), "protocol.ChapterInfo_")
	proto.RegisterType((*Req_ChapterInfo_)(nil), "protocol.Req_ChapterInfo_")
	proto.RegisterType((*Resp_ChapterInfo_)(nil), "protocol.Resp_ChapterInfo_")
	proto.RegisterType((*Push_Table_Update_)(nil), "protocol.Push_Table_Update_")
	proto.RegisterType((*Req_ChapterNode_PickUp_)(nil), "protocol.Req_ChapterNode_PickUp_")
	proto.RegisterType((*Resp_ChapterNode_PickUp_)(nil), "protocol.Resp_ChapterNode_PickUp_")
	proto.RegisterType((*Req_ChapterBattleSet_)(nil), "protocol.Req_ChapterBattleSet_")
	proto.RegisterType((*Resp_ChapterBattleSet_)(nil), "protocol.Resp_ChapterBattleSet_")
	proto.RegisterType((*Req_ChapterBattleReset_)(nil), "protocol.Req_ChapterBattleReset_")
	proto.RegisterType((*Resp_ChapterBattleReset_)(nil), "protocol.Resp_ChapterBattleReset_")
	proto.RegisterType((*Req_ChapterNodeState_)(nil), "protocol.Req_ChapterNodeState_")
	proto.RegisterType((*Resp_ChapterNodeState_)(nil), "protocol.Resp_ChapterNodeState_")
	proto.RegisterType((*Req_ChapterState_)(nil), "protocol.Req_ChapterState_")
	proto.RegisterType((*Resp_ChapterState_)(nil), "protocol.Resp_ChapterState_")
	proto.RegisterType((*Req_ChapterMopUp_)(nil), "protocol.Req_ChapterMopUp_")
	proto.RegisterType((*Resp_ChapterMopUp_)(nil), "protocol.Resp_ChapterMopUp_")
	proto.RegisterType((*Req_Adventure_Choose_)(nil), "protocol.Req_Adventure_Choose_")
	proto.RegisterType((*Resp_Adventure_Choose_)(nil), "protocol.Resp_Adventure_Choose_")
	proto.RegisterType((*Req_MysticStore_)(nil), "protocol.Req_MysticStore_")
	proto.RegisterType((*Resp_MysticStore_)(nil), "protocol.Resp_MysticStore_")
	proto.RegisterType((*Req_Buy_MysticStore_)(nil), "protocol.Req_Buy_MysticStore_")
	proto.RegisterType((*Resp_Buy_MysticStore_)(nil), "protocol.Resp_Buy_MysticStore_")
	proto.RegisterType((*Req_Leave_MysticStore_)(nil), "protocol.Req_Leave_MysticStore_")
	proto.RegisterType((*Req_Altar_)(nil), "protocol.Req_Altar_")
	proto.RegisterType((*Resp_Altar_)(nil), "protocol.Resp_Altar_")
	proto.RegisterType((*Req_Buy_Altar_)(nil), "protocol.Req_Buy_Altar_")
	proto.RegisterType((*Resp_Buy_Altar_)(nil), "protocol.Resp_Buy_Altar_")
}

func init() { proto.RegisterFile("battle.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x55, 0xdb, 0x4e, 0xdb, 0x40,
	0x10, 0x95, 0x01, 0x43, 0x98, 0x84, 0x9b, 0xb9, 0xd4, 0xe5, 0xa1, 0x45, 0x5b, 0x51, 0x90, 0xa8,
	0xf2, 0xc0, 0x13, 0x4f, 0x55, 0xb9, 0x54, 0x14, 0x01, 0x15, 0x4a, 0x4a, 0x5f, 0x2a, 0x61, 0x99,
	0x64, 0xdb, 0xa4, 0x58, 0x59, 0xe3, 0x5d, 0x28, 0xfc, 0x59, 0x7f, 0xa7, 0x7f, 0xd2, 0xdd, 0xd9,
	0xb5, 0xbd, 0xcb, 0xc5, 0x84, 0x4a, 0x7d, 0x8a, 0xd6, 0x3b, 0x7b, 0xe6, 0xcc, 0x39, 0x33, 0x13,
	0x68, 0x9c, 0xc7, 0x42, 0x24, 0xb4, 0x99, 0x66, 0x4c, 0xb0, 0xa0, 0x86, 0x3f, 0x1d, 0x96, 0x2c,
	0xc3, 0x79, 0xcc, 0xcd, 0x57, 0x72, 0x08, 0xd3, 0x9f, 0x59, 0x97, 0xee, 0xc4, 0xa2, 0xd3, 0x3b,
	0x18, 0x7c, 0x67, 0x51, 0xd0, 0x80, 0xb1, 0xb6, 0xa0, 0x69, 0xe8, 0xad, 0x78, 0xeb, 0x7e, 0xb0,
	0x01, 0xb5, 0x63, 0x36, 0xe0, 0x82, 0x66, 0x3c, 0x1c, 0x59, 0x19, 0x5d, 0xaf, 0x6f, 0xbe, 0x6c,
	0xe6, 0x40, 0xcd, 0x1d, 0xc4, 0xff, 0x44, 0x33, 0x86, 0x4f, 0xc9, 0x1f, 0x0f, 0x26, 0x15, 0x9a,
	0x06, 0xaa, 0xc3, 0xe8, 0x41, 0xf7, 0xc6, 0xe0, 0xc8, 0xc3, 0xd7, 0xbe, 0x90, 0x10, 0xea, 0x30,
	0x03, 0x13, 0x87, 0xf4, 0x76, 0x97, 0x71, 0x11, 0x8e, 0xe2, 0x87, 0x69, 0x18, 0x97, 0x1f, 0xf6,
	0xa9, 0x08, 0xc7, 0xf0, 0xbc, 0x06, 0x13, 0x2d, 0xfa, 0x2b, 0xce, 0xba, 0x3c, 0xf4, 0x31, 0xe9,
	0x52, 0x99, 0x54, 0x5f, 0x44, 0x3a, 0xc7, 0x06, 0xd4, 0x4f, 0xfa, 0x9d, 0x8b, 0x3c, 0x78, 0xbc,
	0x32, 0xb8, 0x09, 0x0d, 0x53, 0x0b, 0x96, 0x1b, 0x4e, 0x60, 0x74, 0x58, 0x46, 0xdf, 0x51, 0x62,
	0x1e, 0xea, 0xdb, 0xdd, 0x6b, 0x3a, 0x10, 0x57, 0x19, 0x3d, 0xd8, 0x0b, 0x6b, 0x32, 0xdc, 0x27,
	0x3f, 0xa1, 0xb1, 0xdb, 0x8b, 0x53, 0x09, 0xa2, 0x83, 0x00, 0x46, 0xe4, 0x9d, 0x67, 0x68, 0x4f,
	0x7e, 0x89, 0xcf, 0x13, 0xac, 0x1f, 0x4b, 0xad, 0x6f, 0x2e, 0x94, 0xe8, 0xc5, 0x55, 0x14, 0xac,
	0x42, 0x2d, 0xd7, 0x49, 0x2a, 0xa0, 0x58, 0xcc, 0xbb, 0x2c, 0xb4, 0x9e, 0xaf, 0x60, 0xb6, 0x45,
	0x2f, 0xa3, 0x07, 0xf3, 0x29, 0x2e, 0x1f, 0x60, 0xae, 0x45, 0x79, 0xea, 0x06, 0x48, 0x49, 0xac,
	0x33, 0x46, 0x3a, 0x92, 0xd8, 0xc1, 0x64, 0x00, 0xc1, 0xc9, 0x15, 0xef, 0x45, 0xc8, 0x2d, 0x3a,
	0x4d, 0xbb, 0xb1, 0xa0, 0xcf, 0x83, 0x90, 0xc1, 0x53, 0xc7, 0xfd, 0x01, 0x1d, 0xaa, 0x70, 0x72,
	0x04, 0x2f, 0xac, 0x8a, 0x54, 0xa5, 0x91, 0xf2, 0xef, 0x34, 0x75, 0x85, 0x94, 0xfd, 0x80, 0x2a,
	0xec, 0x99, 0x86, 0x59, 0x84, 0xa9, 0xd2, 0x66, 0xd5, 0x54, 0xd8, 0x36, 0xe4, 0x0c, 0x42, 0xbb,
	0xfe, 0xa1, 0xe1, 0xde, 0xc2, 0xb8, 0x86, 0x42, 0x9c, 0x47, 0x1b, 0x86, 0xfc, 0xf6, 0x60, 0xd1,
	0xa2, 0xab, 0xdb, 0xbd, 0x4d, 0xc5, 0x3f, 0xba, 0xfe, 0xae, 0x9c, 0x0e, 0x6e, 0x6c, 0xbf, 0x37,
	0x4c, 0xe5, 0xf8, 0xc8, 0xe8, 0x7c, 0xb2, 0xb8, 0x1c, 0x8b, 0xea, 0xd1, 0xb3, 0x4a, 0xf4, 0x51,
	0x9a, 0x2d, 0x58, 0xb2, 0xa5, 0xb1, 0xa8, 0xcb, 0xe1, 0xfb, 0x78, 0x23, 0xb2, 0xb8, 0xe0, 0x3f,
	0x05, 0x7e, 0xbb, 0x17, 0x67, 0x54, 0x8b, 0x43, 0x56, 0x1d, 0x8b, 0xf4, 0x43, 0x09, 0x75, 0xa7,
	0x6a, 0xb2, 0xec, 0x6a, 0x6f, 0xc7, 0x91, 0x1f, 0x8e, 0x6c, 0x8a, 0x57, 0x5b, 0x60, 0x63, 0x55,
	0x99, 0xa2, 0x68, 0xa8, 0x28, 0xb3, 0x12, 0xde, 0x80, 0xdf, 0xa2, 0x34, 0xc9, 0x4b, 0x5f, 0xb0,
	0x2d, 0xa2, 0x89, 0x31, 0x28, 0x74, 0xab, 0x2c, 0x33, 0x91, 0xa6, 0x1a, 0x8d, 0x82, 0xc2, 0x03,
	0xe9, 0x8b, 0x74, 0xba, 0xea, 0x0b, 0x08, 0x6c, 0xa4, 0x27, 0x1f, 0x04, 0xeb, 0x30, 0xb9, 0xdb,
	0xa3, 0x5c, 0x98, 0x19, 0x56, 0xae, 0x2f, 0xda, 0x13, 0x22, 0xaf, 0xcc, 0xda, 0x99, 0x55, 0x2b,
	0x34, 0x3d, 0x4d, 0xd5, 0xfe, 0xc3, 0xf5, 0x46, 0x5e, 0x3b, 0xe4, 0xf0, 0xd2, 0x15, 0xf7, 0xd0,
	0x65, 0x63, 0x22, 0x9c, 0x94, 0x5e, 0x55, 0x4a, 0x7b, 0xdb, 0x92, 0x6f, 0xda, 0x8d, 0x62, 0x95,
	0x49, 0x54, 0xc6, 0xf8, 0x13, 0x6e, 0xdc, 0xd9, 0x7d, 0xda, 0x93, 0x39, 0x45, 0x40, 0xbd, 0x55,
	0x23, 0xa8, 0x4b, 0xd9, 0x36, 0x0e, 0xdc, 0x47, 0xb7, 0x76, 0xb8, 0x57, 0xb5, 0x96, 0xa5, 0x55,
	0xb8, 0xe5, 0x8e, 0x6f, 0xb9, 0xe8, 0x77, 0xda, 0x82, 0x65, 0xd5, 0xd4, 0x48, 0x66, 0xb6, 0x9e,
	0xf3, 0x40, 0x76, 0xf5, 0x3e, 0x63, 0x5d, 0x9e, 0xef, 0x46, 0xb9, 0x62, 0x7d, 0xfc, 0x60, 0xfe,
	0xb5, 0x1e, 0xfb, 0x4f, 0x90, 0x61, 0x27, 0x59, 0xbf, 0x43, 0xcd, 0x3c, 0x3e, 0xc6, 0x71, 0x0d,
	0x16, 0x14, 0xc7, 0x9d, 0xab, 0xdb, 0x8a, 0xb4, 0x8a, 0xdc, 0x7b, 0x25, 0xb6, 0x24, 0x77, 0x2f,
	0xb2, 0xe0, 0xe3, 0x55, 0xae, 0x1c, 0xec, 0xe8, 0xcb, 0xe8, 0x88, 0xc6, 0xd7, 0xd4, 0x01, 0x20,
	0x0d, 0x00, 0xb4, 0x31, 0x11, 0x71, 0x16, 0x49, 0x53, 0xeb, 0x5a, 0x77, 0x3c, 0xda, 0xe8, 0x43,
	0x55, 0x3b, 0x52, 0x49, 0xe2, 0x0c, 0xa6, 0xf3, 0x6a, 0xff, 0x0b, 0xfe, 0x16, 0xcc, 0x14, 0x22,
	0x3d, 0x2b, 0xc1, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x31, 0xdf, 0xd0, 0xd3, 0x08, 0x00,
	0x00,
}
