// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Chat_Info_ struct {
	Type             *int32  `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	Time             *int64  `protobuf:"varint,2,opt,name=Time" json:"Time,omitempty"`
	Uid              *int64  `protobuf:"varint,3,opt,name=Uid" json:"Uid,omitempty"`
	Name             *string `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
	Content          *string `protobuf:"bytes,5,opt,name=Content" json:"Content,omitempty"`
	Icon             *int32  `protobuf:"varint,6,opt,name=Icon" json:"Icon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Chat_Info_) Reset()                    { *m = Chat_Info_{} }
func (m *Chat_Info_) String() string            { return proto.CompactTextString(m) }
func (*Chat_Info_) ProtoMessage()               {}
func (*Chat_Info_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Chat_Info_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Chat_Info_) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Chat_Info_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Chat_Info_) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Chat_Info_) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Chat_Info_) GetIcon() int32 {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return 0
}

type Marquee_Info_ struct {
	Type             *int32  `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	Content          *string `protobuf:"bytes,2,opt,name=Content" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Marquee_Info_) Reset()                    { *m = Marquee_Info_{} }
func (m *Marquee_Info_) String() string            { return proto.CompactTextString(m) }
func (*Marquee_Info_) ProtoMessage()               {}
func (*Marquee_Info_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *Marquee_Info_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Marquee_Info_) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type GamePush_Info_ struct {
	Type             *int32   `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	Content          *string  `protobuf:"bytes,2,opt,name=Content" json:"Content,omitempty"`
	Args             []string `protobuf:"bytes,3,rep,name=Args" json:"Args,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GamePush_Info_) Reset()                    { *m = GamePush_Info_{} }
func (m *GamePush_Info_) String() string            { return proto.CompactTextString(m) }
func (*GamePush_Info_) ProtoMessage()               {}
func (*GamePush_Info_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *GamePush_Info_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *GamePush_Info_) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *GamePush_Info_) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type Resp_Marquee_ struct {
	MarqueeInfos     []*Marquee_Info_  `protobuf:"bytes,1,rep,name=MarqueeInfos" json:"MarqueeInfos,omitempty"`
	PushInfos        []*GamePush_Info_ `protobuf:"bytes,2,rep,name=PushInfos" json:"PushInfos,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Resp_Marquee_) Reset()                    { *m = Resp_Marquee_{} }
func (m *Resp_Marquee_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Marquee_) ProtoMessage()               {}
func (*Resp_Marquee_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *Resp_Marquee_) GetMarqueeInfos() []*Marquee_Info_ {
	if m != nil {
		return m.MarqueeInfos
	}
	return nil
}

func (m *Resp_Marquee_) GetPushInfos() []*GamePush_Info_ {
	if m != nil {
		return m.PushInfos
	}
	return nil
}

type Req_Chat_Info_ struct {
	Uid              *int64 `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Type             *int32 `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Chat_Info_) Reset()                    { *m = Req_Chat_Info_{} }
func (m *Req_Chat_Info_) String() string            { return proto.CompactTextString(m) }
func (*Req_Chat_Info_) ProtoMessage()               {}
func (*Req_Chat_Info_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *Req_Chat_Info_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Req_Chat_Info_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type Req_Chat_Send_ struct {
	Uid              *int64  `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	DecUid           *int64  `protobuf:"varint,3,opt,name=DecUid" json:"DecUid,omitempty"`
	DecName          *string `protobuf:"bytes,4,opt,name=DecName" json:"DecName,omitempty"`
	Content          *string `protobuf:"bytes,5,opt,name=Content" json:"Content,omitempty"`
	Icon             *int32  `protobuf:"varint,6,opt,name=Icon" json:"Icon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Chat_Send_) Reset()                    { *m = Req_Chat_Send_{} }
func (m *Req_Chat_Send_) String() string            { return proto.CompactTextString(m) }
func (*Req_Chat_Send_) ProtoMessage()               {}
func (*Req_Chat_Send_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *Req_Chat_Send_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Req_Chat_Send_) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Req_Chat_Send_) GetDecUid() int64 {
	if m != nil && m.DecUid != nil {
		return *m.DecUid
	}
	return 0
}

func (m *Req_Chat_Send_) GetDecName() string {
	if m != nil && m.DecName != nil {
		return *m.DecName
	}
	return ""
}

func (m *Req_Chat_Send_) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Req_Chat_Send_) GetIcon() int32 {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return 0
}

// 请求发送聊天结果
type Resp_Update_Player_ChatInfo_ struct {
	NextChatTime     *int64        `protobuf:"varint,1,opt,name=NextChatTime" json:"NextChatTime,omitempty"`
	Cost             *Reward_Info_ `protobuf:"bytes,2,opt,name=Cost" json:"Cost,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Resp_Update_Player_ChatInfo_) Reset()                    { *m = Resp_Update_Player_ChatInfo_{} }
func (m *Resp_Update_Player_ChatInfo_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Update_Player_ChatInfo_) ProtoMessage()               {}
func (*Resp_Update_Player_ChatInfo_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *Resp_Update_Player_ChatInfo_) GetNextChatTime() int64 {
	if m != nil && m.NextChatTime != nil {
		return *m.NextChatTime
	}
	return 0
}

func (m *Resp_Update_Player_ChatInfo_) GetCost() *Reward_Info_ {
	if m != nil {
		return m.Cost
	}
	return nil
}

type Resp_Chat_Info_ struct {
	Uid              *int64        `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Type             *int32        `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	ChatInfos        []*Chat_Info_ `protobuf:"bytes,3,rep,name=ChatInfos" json:"ChatInfos,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Resp_Chat_Info_) Reset()                    { *m = Resp_Chat_Info_{} }
func (m *Resp_Chat_Info_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Chat_Info_) ProtoMessage()               {}
func (*Resp_Chat_Info_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *Resp_Chat_Info_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Resp_Chat_Info_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Resp_Chat_Info_) GetChatInfos() []*Chat_Info_ {
	if m != nil {
		return m.ChatInfos
	}
	return nil
}

type Resp_Chat_Send_ struct {
	DecUid           *int64        `protobuf:"varint,1,opt,name=DecUid" json:"DecUid,omitempty"`
	ChatInfos        []*Chat_Info_ `protobuf:"bytes,2,rep,name=ChatInfos" json:"ChatInfos,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Resp_Chat_Send_) Reset()                    { *m = Resp_Chat_Send_{} }
func (m *Resp_Chat_Send_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Chat_Send_) ProtoMessage()               {}
func (*Resp_Chat_Send_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *Resp_Chat_Send_) GetDecUid() int64 {
	if m != nil && m.DecUid != nil {
		return *m.DecUid
	}
	return 0
}

func (m *Resp_Chat_Send_) GetChatInfos() []*Chat_Info_ {
	if m != nil {
		return m.ChatInfos
	}
	return nil
}

type Resp_Chat_PriSend_ struct {
	DecUid           []int64       `protobuf:"varint,1,rep,name=DecUid" json:"DecUid,omitempty"`
	ChatInfos        []*Chat_Info_ `protobuf:"bytes,2,rep,name=ChatInfos" json:"ChatInfos,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Resp_Chat_PriSend_) Reset()                    { *m = Resp_Chat_PriSend_{} }
func (m *Resp_Chat_PriSend_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Chat_PriSend_) ProtoMessage()               {}
func (*Resp_Chat_PriSend_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *Resp_Chat_PriSend_) GetDecUid() []int64 {
	if m != nil {
		return m.DecUid
	}
	return nil
}

func (m *Resp_Chat_PriSend_) GetChatInfos() []*Chat_Info_ {
	if m != nil {
		return m.ChatInfos
	}
	return nil
}

// 请求 竞技场聊天
type Req_Battle_Chat_Send_ struct {
	Uid              *int64  `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	DecUid           *int64  `protobuf:"varint,3,opt,name=DecUid" json:"DecUid,omitempty"`
	Content          *string `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Battle_Chat_Send_) Reset()                    { *m = Req_Battle_Chat_Send_{} }
func (m *Req_Battle_Chat_Send_) String() string            { return proto.CompactTextString(m) }
func (*Req_Battle_Chat_Send_) ProtoMessage()               {}
func (*Req_Battle_Chat_Send_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *Req_Battle_Chat_Send_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Req_Battle_Chat_Send_) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Req_Battle_Chat_Send_) GetDecUid() int64 {
	if m != nil && m.DecUid != nil {
		return *m.DecUid
	}
	return 0
}

func (m *Req_Battle_Chat_Send_) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type Resp_Battle_Chat_Info_ struct {
	DecUid           []int64       `protobuf:"varint,1,rep,name=DecUid" json:"DecUid,omitempty"`
	ChatInfos        []*Chat_Info_ `protobuf:"bytes,2,rep,name=ChatInfos" json:"ChatInfos,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Resp_Battle_Chat_Info_) Reset()                    { *m = Resp_Battle_Chat_Info_{} }
func (m *Resp_Battle_Chat_Info_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Battle_Chat_Info_) ProtoMessage()               {}
func (*Resp_Battle_Chat_Info_) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11} }

func (m *Resp_Battle_Chat_Info_) GetDecUid() []int64 {
	if m != nil {
		return m.DecUid
	}
	return nil
}

func (m *Resp_Battle_Chat_Info_) GetChatInfos() []*Chat_Info_ {
	if m != nil {
		return m.ChatInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*Chat_Info_)(nil), "protocol.Chat_Info_")
	proto.RegisterType((*Marquee_Info_)(nil), "protocol.Marquee_Info_")
	proto.RegisterType((*GamePush_Info_)(nil), "protocol.GamePush_Info_")
	proto.RegisterType((*Resp_Marquee_)(nil), "protocol.Resp_Marquee_")
	proto.RegisterType((*Req_Chat_Info_)(nil), "protocol.Req_Chat_Info_")
	proto.RegisterType((*Req_Chat_Send_)(nil), "protocol.Req_Chat_Send_")
	proto.RegisterType((*Resp_Update_Player_ChatInfo_)(nil), "protocol.Resp_Update_Player_ChatInfo_")
	proto.RegisterType((*Resp_Chat_Info_)(nil), "protocol.Resp_Chat_Info_")
	proto.RegisterType((*Resp_Chat_Send_)(nil), "protocol.Resp_Chat_Send_")
	proto.RegisterType((*Resp_Chat_PriSend_)(nil), "protocol.Resp_Chat_PriSend_")
	proto.RegisterType((*Req_Battle_Chat_Send_)(nil), "protocol.Req_Battle_Chat_Send_")
	proto.RegisterType((*Resp_Battle_Chat_Info_)(nil), "protocol.Resp_Battle_Chat_Info_")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4f, 0xc2, 0x50,
	0x0c, 0xc7, 0xc3, 0x06, 0xe8, 0x3a, 0x7e, 0x24, 0x0b, 0xe2, 0x62, 0x3c, 0x98, 0xc5, 0x44, 0x12,
	0xe2, 0x0e, 0xdc, 0x3d, 0x28, 0x26, 0x06, 0x13, 0x08, 0x82, 0x5c, 0xbc, 0x2c, 0x8f, 0xad, 0x0a,
	0x01, 0xb7, 0xb1, 0x3d, 0xa2, 0xfc, 0xf7, 0xbe, 0xf5, 0xb1, 0x6c, 0x04, 0x63, 0x90, 0xd3, 0xd6,
	0xd7, 0xf6, 0xd3, 0x6f, 0xbf, 0x05, 0x70, 0x67, 0x8c, 0xdb, 0x61, 0x14, 0xf0, 0xc0, 0x38, 0xa5,
	0x8f, 0x1b, 0x2c, 0x2f, 0x60, 0xca, 0x62, 0x94, 0xaf, 0xd6, 0x14, 0xa0, 0x2b, 0x6a, 0x9c, 0x9e,
	0xff, 0x1e, 0x38, 0x46, 0x05, 0x8a, 0xaf, 0x9b, 0x10, 0xcd, 0xc2, 0x55, 0xa1, 0x55, 0xa2, 0x68,
	0xfe, 0x89, 0xa6, 0x22, 0x22, 0xd5, 0xd0, 0x41, 0x9d, 0xcc, 0x3d, 0x53, 0xa5, 0x40, 0xa4, 0x06,
	0x4c, 0xa4, 0x8a, 0x22, 0xd2, 0x8c, 0x3a, 0x9c, 0x74, 0x03, 0x9f, 0xa3, 0xcf, 0xcd, 0x12, 0x3d,
	0x88, 0x74, 0xcf, 0x0d, 0x7c, 0xb3, 0x9c, 0x70, 0x2c, 0x1b, 0xaa, 0x7d, 0x16, 0xad, 0xd6, 0x88,
	0xbf, 0x8e, 0xc9, 0x75, 0x27, 0x93, 0x34, 0xeb, 0x0e, 0x6a, 0x4f, 0x02, 0x3e, 0x5c, 0xc7, 0xb3,
	0x83, 0x1a, 0x92, 0xf4, 0x7d, 0xf4, 0x11, 0x0b, 0x6d, 0xaa, 0x68, 0x5f, 0x40, 0x75, 0x84, 0x71,
	0xe8, 0xa4, 0x33, 0x8d, 0x5b, 0xa8, 0x6c, 0xff, 0x13, 0x5a, 0x2c, 0x28, 0x6a, 0x4b, 0xef, 0x9c,
	0xdb, 0xa9, 0x21, 0xf6, 0xae, 0xba, 0x36, 0x68, 0xc9, 0x68, 0x59, 0xab, 0x50, 0xad, 0x99, 0xd5,
	0xee, 0x2a, 0xb3, 0xda, 0x50, 0x1b, 0xe1, 0xca, 0xc9, 0x79, 0xb8, 0xf5, 0xa9, 0x90, 0xfa, 0x44,
	0xc2, 0x15, 0x32, 0x62, 0x91, 0x2b, 0x1e, 0xa3, 0xef, 0xed, 0x17, 0x93, 0xa9, 0x72, 0xa9, 0x1a,
	0x94, 0x1f, 0xd1, 0xcd, 0x2c, 0x17, 0x5b, 0x8b, 0xf8, 0x70, 0xd7, 0xdf, 0xe0, 0x92, 0x6c, 0x98,
	0x84, 0x1e, 0xe3, 0xe8, 0x0c, 0x97, 0x6c, 0x83, 0x11, 0xcd, 0x96, 0x3a, 0x1b, 0x50, 0x19, 0xe0,
	0x37, 0x4f, 0x1e, 0xe8, 0xca, 0x52, 0xc3, 0x35, 0x14, 0xbb, 0x41, 0x2c, 0x8d, 0xd5, 0x3b, 0xcd,
	0x6c, 0xef, 0x11, 0x7e, 0xb1, 0xc8, 0xdb, 0x6e, 0x3d, 0x81, 0x3a, 0xb1, 0x0f, 0x5a, 0xdb, 0xb8,
	0x01, 0x2d, 0x1d, 0x2b, 0x6f, 0xa4, 0x77, 0x1a, 0x19, 0x38, 0x63, 0x58, 0xcf, 0x79, 0xac, 0x34,
	0x28, 0x73, 0x41, 0x92, 0x77, 0x58, 0xca, 0x1f, 0xac, 0x3e, 0x18, 0x19, 0x6b, 0x18, 0xcd, 0xf7,
	0x71, 0xea, 0x7f, 0x70, 0x63, 0x38, 0x4b, 0x4e, 0xf7, 0xc0, 0x38, 0x5f, 0xe2, 0xf1, 0x17, 0x4c,
	0x0f, 0x46, 0x17, 0xb4, 0x5e, 0xa0, 0x49, 0x1a, 0xf3, 0x54, 0xe9, 0xe6, 0xb1, 0x3a, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xfb, 0x90, 0x4e, 0x53, 0xf2, 0x03, 0x00, 0x00,
}
