// Code generated by protoc-gen-go.
// source: friend.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Friend_Info_ struct {
	Uid              *int64 `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	GiftSend         *bool  `protobuf:"varint,2,opt,name=GiftSend" json:"GiftSend,omitempty"`
	GiftState        *int32 `protobuf:"varint,3,opt,name=GiftState" json:"GiftState,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Friend_Info_) Reset()                    { *m = Friend_Info_{} }
func (m *Friend_Info_) String() string            { return proto.CompactTextString(m) }
func (*Friend_Info_) ProtoMessage()               {}
func (*Friend_Info_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *Friend_Info_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Friend_Info_) GetGiftSend() bool {
	if m != nil && m.GiftSend != nil {
		return *m.GiftSend
	}
	return false
}

func (m *Friend_Info_) GetGiftState() int32 {
	if m != nil && m.GiftState != nil {
		return *m.GiftState
	}
	return 0
}

type Req_Friend_Info_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Friend_Info_) Reset()                    { *m = Req_Friend_Info_{} }
func (m *Req_Friend_Info_) String() string            { return proto.CompactTextString(m) }
func (*Req_Friend_Info_) ProtoMessage()               {}
func (*Req_Friend_Info_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

type Resp_Friend_Info_ struct {
	GiftSendNum      *int32          `protobuf:"varint,1,opt,name=GiftSendNum" json:"GiftSendNum,omitempty"`
	GiftSendNumMax   *int32          `protobuf:"varint,2,opt,name=GiftSendNumMax" json:"GiftSendNumMax,omitempty"`
	GiftRecvNum      *int32          `protobuf:"varint,3,opt,name=GiftRecvNum" json:"GiftRecvNum,omitempty"`
	GiftRecvNumMax   *int32          `protobuf:"varint,4,opt,name=GiftRecvNumMax" json:"GiftRecvNumMax,omitempty"`
	Infos            []*Friend_Info_ `protobuf:"bytes,5,rep,name=Infos" json:"Infos,omitempty"`
	Applies          []int64         `protobuf:"varint,6,rep,name=Applies" json:"Applies,omitempty"`
	FriendNumMax     *int32          `protobuf:"varint,7,opt,name=FriendNumMax" json:"FriendNumMax,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Friend_Info_) Reset()                    { *m = Resp_Friend_Info_{} }
func (m *Resp_Friend_Info_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Friend_Info_) ProtoMessage()               {}
func (*Resp_Friend_Info_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *Resp_Friend_Info_) GetGiftSendNum() int32 {
	if m != nil && m.GiftSendNum != nil {
		return *m.GiftSendNum
	}
	return 0
}

func (m *Resp_Friend_Info_) GetGiftSendNumMax() int32 {
	if m != nil && m.GiftSendNumMax != nil {
		return *m.GiftSendNumMax
	}
	return 0
}

func (m *Resp_Friend_Info_) GetGiftRecvNum() int32 {
	if m != nil && m.GiftRecvNum != nil {
		return *m.GiftRecvNum
	}
	return 0
}

func (m *Resp_Friend_Info_) GetGiftRecvNumMax() int32 {
	if m != nil && m.GiftRecvNumMax != nil {
		return *m.GiftRecvNumMax
	}
	return 0
}

func (m *Resp_Friend_Info_) GetInfos() []*Friend_Info_ {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *Resp_Friend_Info_) GetApplies() []int64 {
	if m != nil {
		return m.Applies
	}
	return nil
}

func (m *Resp_Friend_Info_) GetFriendNumMax() int32 {
	if m != nil && m.FriendNumMax != nil {
		return *m.FriendNumMax
	}
	return 0
}

type Req_Friend_Apply_ struct {
	SrcUid           *int64 `protobuf:"varint,1,opt,name=SrcUid" json:"SrcUid,omitempty"`
	DecUid           *int64 `protobuf:"varint,2,opt,name=DecUid" json:"DecUid,omitempty"`
	Type             *int32 `protobuf:"varint,3,opt,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Friend_Apply_) Reset()                    { *m = Req_Friend_Apply_{} }
func (m *Req_Friend_Apply_) String() string            { return proto.CompactTextString(m) }
func (*Req_Friend_Apply_) ProtoMessage()               {}
func (*Req_Friend_Apply_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *Req_Friend_Apply_) GetSrcUid() int64 {
	if m != nil && m.SrcUid != nil {
		return *m.SrcUid
	}
	return 0
}

func (m *Req_Friend_Apply_) GetDecUid() int64 {
	if m != nil && m.DecUid != nil {
		return *m.DecUid
	}
	return 0
}

func (m *Req_Friend_Apply_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type Resp_Friend_Apply_ struct {
	SrcUid           *int64 `protobuf:"varint,1,opt,name=SrcUid" json:"SrcUid,omitempty"`
	DecUid           *int64 `protobuf:"varint,2,opt,name=DecUid" json:"DecUid,omitempty"`
	Type             *int32 `protobuf:"varint,3,opt,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_Friend_Apply_) Reset()                    { *m = Resp_Friend_Apply_{} }
func (m *Resp_Friend_Apply_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Friend_Apply_) ProtoMessage()               {}
func (*Resp_Friend_Apply_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *Resp_Friend_Apply_) GetSrcUid() int64 {
	if m != nil && m.SrcUid != nil {
		return *m.SrcUid
	}
	return 0
}

func (m *Resp_Friend_Apply_) GetDecUid() int64 {
	if m != nil && m.DecUid != nil {
		return *m.DecUid
	}
	return 0
}

func (m *Resp_Friend_Apply_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type Req_Friend_ApplyRet_ struct {
	SrcUid           *int64  `protobuf:"varint,1,opt,name=SrcUid" json:"SrcUid,omitempty"`
	SrcName          *string `protobuf:"bytes,2,opt,name=SrcName" json:"SrcName,omitempty"`
	DecUid           *int64  `protobuf:"varint,3,opt,name=DecUid" json:"DecUid,omitempty"`
	Ret              *int32  `protobuf:"varint,4,opt,name=Ret" json:"Ret,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Friend_ApplyRet_) Reset()                    { *m = Req_Friend_ApplyRet_{} }
func (m *Req_Friend_ApplyRet_) String() string            { return proto.CompactTextString(m) }
func (*Req_Friend_ApplyRet_) ProtoMessage()               {}
func (*Req_Friend_ApplyRet_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *Req_Friend_ApplyRet_) GetSrcUid() int64 {
	if m != nil && m.SrcUid != nil {
		return *m.SrcUid
	}
	return 0
}

func (m *Req_Friend_ApplyRet_) GetSrcName() string {
	if m != nil && m.SrcName != nil {
		return *m.SrcName
	}
	return ""
}

func (m *Req_Friend_ApplyRet_) GetDecUid() int64 {
	if m != nil && m.DecUid != nil {
		return *m.DecUid
	}
	return 0
}

func (m *Req_Friend_ApplyRet_) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

type Resp_Friend_ApplyRet_ struct {
	SrcUid           *int64  `protobuf:"varint,1,opt,name=SrcUid" json:"SrcUid,omitempty"`
	SrcName          *string `protobuf:"bytes,2,opt,name=SrcName" json:"SrcName,omitempty"`
	DecUid           *int64  `protobuf:"varint,3,opt,name=DecUid" json:"DecUid,omitempty"`
	Ret              *int32  `protobuf:"varint,4,opt,name=Ret" json:"Ret,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_Friend_ApplyRet_) Reset()                    { *m = Resp_Friend_ApplyRet_{} }
func (m *Resp_Friend_ApplyRet_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Friend_ApplyRet_) ProtoMessage()               {}
func (*Resp_Friend_ApplyRet_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *Resp_Friend_ApplyRet_) GetSrcUid() int64 {
	if m != nil && m.SrcUid != nil {
		return *m.SrcUid
	}
	return 0
}

func (m *Resp_Friend_ApplyRet_) GetSrcName() string {
	if m != nil && m.SrcName != nil {
		return *m.SrcName
	}
	return ""
}

func (m *Resp_Friend_ApplyRet_) GetDecUid() int64 {
	if m != nil && m.DecUid != nil {
		return *m.DecUid
	}
	return 0
}

func (m *Resp_Friend_ApplyRet_) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

type Req_Friend_Find_ struct {
	Name             *string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Uid              *int64  `protobuf:"varint,2,opt,name=Uid" json:"Uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Friend_Find_) Reset()                    { *m = Req_Friend_Find_{} }
func (m *Req_Friend_Find_) String() string            { return proto.CompactTextString(m) }
func (*Req_Friend_Find_) ProtoMessage()               {}
func (*Req_Friend_Find_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

func (m *Req_Friend_Find_) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Req_Friend_Find_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

type Resp_Friend_Find_ struct {
	Infos            []*Player_Info_ `protobuf:"bytes,1,rep,name=Infos" json:"Infos,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Friend_Find_) Reset()                    { *m = Resp_Friend_Find_{} }
func (m *Resp_Friend_Find_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Friend_Find_) ProtoMessage()               {}
func (*Resp_Friend_Find_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func (m *Resp_Friend_Find_) GetInfos() []*Player_Info_ {
	if m != nil {
		return m.Infos
	}
	return nil
}

type Resp_PlayerUpdate_Friend_ struct {
	GiftSendNum      *int32          `protobuf:"varint,1,opt,name=GiftSendNum" json:"GiftSendNum,omitempty"`
	GiftRecvNum      *int32          `protobuf:"varint,2,opt,name=GiftRecvNum" json:"GiftRecvNum,omitempty"`
	Infos            []*Friend_Info_ `protobuf:"bytes,3,rep,name=Infos" json:"Infos,omitempty"`
	Applies          []int64         `protobuf:"varint,4,rep,name=Applies" json:"Applies,omitempty"`
	ChannelFriends   []*Friend_Info_ `protobuf:"bytes,5,rep,name=ChannelFriends" json:"ChannelFriends,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_PlayerUpdate_Friend_) Reset()                    { *m = Resp_PlayerUpdate_Friend_{} }
func (m *Resp_PlayerUpdate_Friend_) String() string            { return proto.CompactTextString(m) }
func (*Resp_PlayerUpdate_Friend_) ProtoMessage()               {}
func (*Resp_PlayerUpdate_Friend_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{9} }

func (m *Resp_PlayerUpdate_Friend_) GetGiftSendNum() int32 {
	if m != nil && m.GiftSendNum != nil {
		return *m.GiftSendNum
	}
	return 0
}

func (m *Resp_PlayerUpdate_Friend_) GetGiftRecvNum() int32 {
	if m != nil && m.GiftRecvNum != nil {
		return *m.GiftRecvNum
	}
	return 0
}

func (m *Resp_PlayerUpdate_Friend_) GetInfos() []*Friend_Info_ {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *Resp_PlayerUpdate_Friend_) GetApplies() []int64 {
	if m != nil {
		return m.Applies
	}
	return nil
}

func (m *Resp_PlayerUpdate_Friend_) GetChannelFriends() []*Friend_Info_ {
	if m != nil {
		return m.ChannelFriends
	}
	return nil
}

// 请求好友删除
type Req_Friend_Del_ struct {
	SrcUid           *int64 `protobuf:"varint,1,opt,name=SrcUid" json:"SrcUid,omitempty"`
	DecUid           *int64 `protobuf:"varint,2,opt,name=DecUid" json:"DecUid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Friend_Del_) Reset()                    { *m = Req_Friend_Del_{} }
func (m *Req_Friend_Del_) String() string            { return proto.CompactTextString(m) }
func (*Req_Friend_Del_) ProtoMessage()               {}
func (*Req_Friend_Del_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{10} }

func (m *Req_Friend_Del_) GetSrcUid() int64 {
	if m != nil && m.SrcUid != nil {
		return *m.SrcUid
	}
	return 0
}

func (m *Req_Friend_Del_) GetDecUid() int64 {
	if m != nil && m.DecUid != nil {
		return *m.DecUid
	}
	return 0
}

// 响应好友删除
type Resp_Friend_Del_ struct {
	SrcUid           *int64 `protobuf:"varint,1,opt,name=SrcUid" json:"SrcUid,omitempty"`
	DecUid           *int64 `protobuf:"varint,2,opt,name=DecUid" json:"DecUid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_Friend_Del_) Reset()                    { *m = Resp_Friend_Del_{} }
func (m *Resp_Friend_Del_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Friend_Del_) ProtoMessage()               {}
func (*Resp_Friend_Del_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{11} }

func (m *Resp_Friend_Del_) GetSrcUid() int64 {
	if m != nil && m.SrcUid != nil {
		return *m.SrcUid
	}
	return 0
}

func (m *Resp_Friend_Del_) GetDecUid() int64 {
	if m != nil && m.DecUid != nil {
		return *m.DecUid
	}
	return 0
}

// 客户端请求好友礼品赠送
type Req_Friend_GiftSend_ struct {
	SrcUid           *int64  `protobuf:"varint,1,opt,name=SrcUid" json:"SrcUid,omitempty"`
	DecUid           []int64 `protobuf:"varint,2,rep,name=DecUid" json:"DecUid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Friend_GiftSend_) Reset()                    { *m = Req_Friend_GiftSend_{} }
func (m *Req_Friend_GiftSend_) String() string            { return proto.CompactTextString(m) }
func (*Req_Friend_GiftSend_) ProtoMessage()               {}
func (*Req_Friend_GiftSend_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{12} }

func (m *Req_Friend_GiftSend_) GetSrcUid() int64 {
	if m != nil && m.SrcUid != nil {
		return *m.SrcUid
	}
	return 0
}

func (m *Req_Friend_GiftSend_) GetDecUid() []int64 {
	if m != nil {
		return m.DecUid
	}
	return nil
}

// 响应 客户端请求好友体力赠送
type Resp_Friend_GiftSend_ struct {
	Uid              *int64 `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	DecUid           *int64 `protobuf:"varint,2,opt,name=DecUid" json:"DecUid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_Friend_GiftSend_) Reset()                    { *m = Resp_Friend_GiftSend_{} }
func (m *Resp_Friend_GiftSend_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Friend_GiftSend_) ProtoMessage()               {}
func (*Resp_Friend_GiftSend_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{13} }

func (m *Resp_Friend_GiftSend_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Resp_Friend_GiftSend_) GetDecUid() int64 {
	if m != nil && m.DecUid != nil {
		return *m.DecUid
	}
	return 0
}

// 请求 好友推荐
type Req_Friend_Recomm_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Friend_Recomm_) Reset()                    { *m = Req_Friend_Recomm_{} }
func (m *Req_Friend_Recomm_) String() string            { return proto.CompactTextString(m) }
func (*Req_Friend_Recomm_) ProtoMessage()               {}
func (*Req_Friend_Recomm_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{14} }

// 响应 好友推荐
type Resp_Friend_Recomm_ struct {
	UserID           []int64  `protobuf:"varint,1,rep,name=UserID" json:"UserID,omitempty"`
	Name             []string `protobuf:"bytes,2,rep,name=Name" json:"Name,omitempty"`
	IconID           []int32  `protobuf:"varint,3,rep,name=IconID" json:"IconID,omitempty"`
	IconUrl          []string `protobuf:"bytes,4,rep,name=IconUrl" json:"IconUrl,omitempty"`
	Lv               []int32  `protobuf:"varint,5,rep,name=Lv" json:"Lv,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Resp_Friend_Recomm_) Reset()                    { *m = Resp_Friend_Recomm_{} }
func (m *Resp_Friend_Recomm_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Friend_Recomm_) ProtoMessage()               {}
func (*Resp_Friend_Recomm_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{15} }

func (m *Resp_Friend_Recomm_) GetUserID() []int64 {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *Resp_Friend_Recomm_) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Resp_Friend_Recomm_) GetIconID() []int32 {
	if m != nil {
		return m.IconID
	}
	return nil
}

func (m *Resp_Friend_Recomm_) GetIconUrl() []string {
	if m != nil {
		return m.IconUrl
	}
	return nil
}

func (m *Resp_Friend_Recomm_) GetLv() []int32 {
	if m != nil {
		return m.Lv
	}
	return nil
}

// 客户端请求好友礼品领取
type Req_Friend_GiftRecv_ struct {
	UserID           []int64 `protobuf:"varint,1,rep,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Friend_GiftRecv_) Reset()                    { *m = Req_Friend_GiftRecv_{} }
func (m *Req_Friend_GiftRecv_) String() string            { return proto.CompactTextString(m) }
func (*Req_Friend_GiftRecv_) ProtoMessage()               {}
func (*Req_Friend_GiftRecv_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{16} }

func (m *Req_Friend_GiftRecv_) GetUserID() []int64 {
	if m != nil {
		return m.UserID
	}
	return nil
}

// 响应 好友礼品领取
type Resp_Friend_GiftRecv_ struct {
	Info             []*Friend_Info_ `protobuf:"bytes,1,rep,name=Info" json:"Info,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Friend_GiftRecv_) Reset()                    { *m = Resp_Friend_GiftRecv_{} }
func (m *Resp_Friend_GiftRecv_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Friend_GiftRecv_) ProtoMessage()               {}
func (*Resp_Friend_GiftRecv_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{17} }

func (m *Resp_Friend_GiftRecv_) GetInfo() []*Friend_Info_ {
	if m != nil {
		return m.Info
	}
	return nil
}

// 请求 宝箱助力
type Req_Chest_Help_ struct {
	Idx              *int32 `protobuf:"varint,1,opt,name=Idx" json:"Idx,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Chest_Help_) Reset()                    { *m = Req_Chest_Help_{} }
func (m *Req_Chest_Help_) String() string            { return proto.CompactTextString(m) }
func (*Req_Chest_Help_) ProtoMessage()               {}
func (*Req_Chest_Help_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{18} }

func (m *Req_Chest_Help_) GetIdx() int32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

// 响应 宝箱助力
type Resp_Chest_Help_ struct {
	Timestemp        *int64       `protobuf:"varint,1,opt,name=Timestemp" json:"Timestemp,omitempty"`
	Idx              *int32       `protobuf:"varint,2,opt,name=Idx" json:"Idx,omitempty"`
	ChestInfo        *Chest_Info_ `protobuf:"bytes,3,opt,name=ChestInfo" json:"ChestInfo,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Resp_Chest_Help_) Reset()                    { *m = Resp_Chest_Help_{} }
func (m *Resp_Chest_Help_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Chest_Help_) ProtoMessage()               {}
func (*Resp_Chest_Help_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{19} }

func (m *Resp_Chest_Help_) GetTimestemp() int64 {
	if m != nil && m.Timestemp != nil {
		return *m.Timestemp
	}
	return 0
}

func (m *Resp_Chest_Help_) GetIdx() int32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *Resp_Chest_Help_) GetChestInfo() *Chest_Info_ {
	if m != nil {
		return m.ChestInfo
	}
	return nil
}

// 请求 分享
type Req_Share_ struct {
	Type             *int32 `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Share_) Reset()                    { *m = Req_Share_{} }
func (m *Req_Share_) String() string            { return proto.CompactTextString(m) }
func (*Req_Share_) ProtoMessage()               {}
func (*Req_Share_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{20} }

func (m *Req_Share_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 响应 分享
type Resp_Share_ struct {
	Type             *int32          `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	Timestemp        *int64          `protobuf:"varint,2,opt,name=Timestemp" json:"Timestemp,omitempty"`
	Rewards          []*Reward_Info_ `protobuf:"bytes,3,rep,name=Rewards" json:"Rewards,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Share_) Reset()                    { *m = Resp_Share_{} }
func (m *Resp_Share_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Share_) ProtoMessage()               {}
func (*Resp_Share_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{21} }

func (m *Resp_Share_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Resp_Share_) GetTimestemp() int64 {
	if m != nil && m.Timestemp != nil {
		return *m.Timestemp
	}
	return 0
}

func (m *Resp_Share_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

// 请求 点击分享
type Req_Click_Share_ struct {
	Timestemp        *int64 `protobuf:"varint,1,opt,name=Timestemp" json:"Timestemp,omitempty"`
	UserID           *int64 `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
	ClickUID         *int64 `protobuf:"varint,3,opt,name=ClickUID" json:"ClickUID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Click_Share_) Reset()                    { *m = Req_Click_Share_{} }
func (m *Req_Click_Share_) String() string            { return proto.CompactTextString(m) }
func (*Req_Click_Share_) ProtoMessage()               {}
func (*Req_Click_Share_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{22} }

func (m *Req_Click_Share_) GetTimestemp() int64 {
	if m != nil && m.Timestemp != nil {
		return *m.Timestemp
	}
	return 0
}

func (m *Req_Click_Share_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Click_Share_) GetClickUID() int64 {
	if m != nil && m.ClickUID != nil {
		return *m.ClickUID
	}
	return 0
}

// 响应 点击分享
type Resp_Click_Share_ struct {
	Timestemp        *int64 `protobuf:"varint,1,opt,name=Timestemp" json:"Timestemp,omitempty"`
	UserID           *int64 `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
	ClickUID         *int64 `protobuf:"varint,3,opt,name=ClickUID" json:"ClickUID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_Click_Share_) Reset()                    { *m = Resp_Click_Share_{} }
func (m *Resp_Click_Share_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Click_Share_) ProtoMessage()               {}
func (*Resp_Click_Share_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{23} }

func (m *Resp_Click_Share_) GetTimestemp() int64 {
	if m != nil && m.Timestemp != nil {
		return *m.Timestemp
	}
	return 0
}

func (m *Resp_Click_Share_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Click_Share_) GetClickUID() int64 {
	if m != nil && m.ClickUID != nil {
		return *m.ClickUID
	}
	return 0
}

// 请求 观看广告
type Req_Watch_Adv_ struct {
	Type             *int32 `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Watch_Adv_) Reset()                    { *m = Req_Watch_Adv_{} }
func (m *Req_Watch_Adv_) String() string            { return proto.CompactTextString(m) }
func (*Req_Watch_Adv_) ProtoMessage()               {}
func (*Req_Watch_Adv_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{24} }

func (m *Req_Watch_Adv_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 响应 观看广告
type Resp_Watch_Adv_ struct {
	Rewards          []*Reward_Info_ `protobuf:"bytes,1,rep,name=Rewards" json:"Rewards,omitempty"`
	Type             *int32          `protobuf:"varint,2,opt,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Watch_Adv_) Reset()                    { *m = Resp_Watch_Adv_{} }
func (m *Resp_Watch_Adv_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Watch_Adv_) ProtoMessage()               {}
func (*Resp_Watch_Adv_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{25} }

func (m *Resp_Watch_Adv_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *Resp_Watch_Adv_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 请求 分享小游戏数据
type Req_Share_GameInfo_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Share_GameInfo_) Reset()                    { *m = Req_Share_GameInfo_{} }
func (m *Req_Share_GameInfo_) String() string            { return proto.CompactTextString(m) }
func (*Req_Share_GameInfo_) ProtoMessage()               {}
func (*Req_Share_GameInfo_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{26} }

// 响应 分享小游戏数据
type Resp_Share_GameInfo_ struct {
	Step             *int32      `protobuf:"varint,1,opt,name=Step" json:"Step,omitempty"`
	Score            []int32     `protobuf:"varint,2,rep,name=Score" json:"Score,omitempty"`
	TableInfo        *TableInfo_ `protobuf:"bytes,3,opt,name=TableInfo" json:"TableInfo,omitempty"`
	FamilyIDs        []int32     `protobuf:"varint,4,rep,name=FamilyIDs" json:"FamilyIDs,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Resp_Share_GameInfo_) Reset()                    { *m = Resp_Share_GameInfo_{} }
func (m *Resp_Share_GameInfo_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Share_GameInfo_) ProtoMessage()               {}
func (*Resp_Share_GameInfo_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{27} }

func (m *Resp_Share_GameInfo_) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *Resp_Share_GameInfo_) GetScore() []int32 {
	if m != nil {
		return m.Score
	}
	return nil
}

func (m *Resp_Share_GameInfo_) GetTableInfo() *TableInfo_ {
	if m != nil {
		return m.TableInfo
	}
	return nil
}

func (m *Resp_Share_GameInfo_) GetFamilyIDs() []int32 {
	if m != nil {
		return m.FamilyIDs
	}
	return nil
}

// 请求 获取FB好友数据
type Req_Get_Channel_Friends_ struct {
	Account          []string `protobuf:"bytes,1,rep,name=Account" json:"Account,omitempty"`
	Channel          *int32   `protobuf:"varint,2,opt,name=Channel" json:"Channel,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Req_Get_Channel_Friends_) Reset()                    { *m = Req_Get_Channel_Friends_{} }
func (m *Req_Get_Channel_Friends_) String() string            { return proto.CompactTextString(m) }
func (*Req_Get_Channel_Friends_) ProtoMessage()               {}
func (*Req_Get_Channel_Friends_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{28} }

func (m *Req_Get_Channel_Friends_) GetAccount() []string {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Req_Get_Channel_Friends_) GetChannel() int32 {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return 0
}

// 响应 获取渠道好友数据
type Resp_Get_Channel_Friends_ struct {
	Friends          []*Friend_Info_ `protobuf:"bytes,1,rep,name=Friends" json:"Friends,omitempty"`
	Account          []string        `protobuf:"bytes,2,rep,name=Account" json:"Account,omitempty"`
	MaxChapter       []int32         `protobuf:"varint,3,rep,name=MaxChapter" json:"MaxChapter,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Get_Channel_Friends_) Reset()                    { *m = Resp_Get_Channel_Friends_{} }
func (m *Resp_Get_Channel_Friends_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Get_Channel_Friends_) ProtoMessage()               {}
func (*Resp_Get_Channel_Friends_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{29} }

func (m *Resp_Get_Channel_Friends_) GetFriends() []*Friend_Info_ {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *Resp_Get_Channel_Friends_) GetAccount() []string {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Resp_Get_Channel_Friends_) GetMaxChapter() []int32 {
	if m != nil {
		return m.MaxChapter
	}
	return nil
}

// 请求 记录渠道好友数据
type Req_Set_Channel_Friends_ struct {
	Account          []string `protobuf:"bytes,1,rep,name=Account" json:"Account,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Req_Set_Channel_Friends_) Reset()                    { *m = Req_Set_Channel_Friends_{} }
func (m *Req_Set_Channel_Friends_) String() string            { return proto.CompactTextString(m) }
func (*Req_Set_Channel_Friends_) ProtoMessage()               {}
func (*Req_Set_Channel_Friends_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{30} }

func (m *Req_Set_Channel_Friends_) GetAccount() []string {
	if m != nil {
		return m.Account
	}
	return nil
}

// 请求 好友邀请数据
type Req_Friend_Invite_Info_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Friend_Invite_Info_) Reset()                    { *m = Req_Friend_Invite_Info_{} }
func (m *Req_Friend_Invite_Info_) String() string            { return proto.CompactTextString(m) }
func (*Req_Friend_Invite_Info_) ProtoMessage()               {}
func (*Req_Friend_Invite_Info_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{31} }

// 响应 好友邀请数据
type Resp_Friend_Invite_Info_ struct {
	RecMax           *int32          `protobuf:"varint,1,opt,name=RecMax" json:"RecMax,omitempty"`
	Lv               []int32         `protobuf:"varint,2,rep,name=Lv" json:"Lv,omitempty"`
	Name             []string        `protobuf:"bytes,3,rep,name=Name" json:"Name,omitempty"`
	State            []int32         `protobuf:"varint,4,rep,name=State" json:"State,omitempty"`
	Uid              []int64         `protobuf:"varint,5,rep,name=Uid" json:"Uid,omitempty"`
	MyInviter        *int64          `protobuf:"varint,6,opt,name=MyInviter" json:"MyInviter,omitempty"`
	Rewards          []*Reward_Info_ `protobuf:"bytes,7,rep,name=Rewards" json:"Rewards,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Friend_Invite_Info_) Reset()                    { *m = Resp_Friend_Invite_Info_{} }
func (m *Resp_Friend_Invite_Info_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Friend_Invite_Info_) ProtoMessage()               {}
func (*Resp_Friend_Invite_Info_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{32} }

func (m *Resp_Friend_Invite_Info_) GetRecMax() int32 {
	if m != nil && m.RecMax != nil {
		return *m.RecMax
	}
	return 0
}

func (m *Resp_Friend_Invite_Info_) GetLv() []int32 {
	if m != nil {
		return m.Lv
	}
	return nil
}

func (m *Resp_Friend_Invite_Info_) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Resp_Friend_Invite_Info_) GetState() []int32 {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Resp_Friend_Invite_Info_) GetUid() []int64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *Resp_Friend_Invite_Info_) GetMyInviter() int64 {
	if m != nil && m.MyInviter != nil {
		return *m.MyInviter
	}
	return 0
}

func (m *Resp_Friend_Invite_Info_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

// 请求 领取邀请奖励
type Req_Recv_Invite_ struct {
	Uid              *int64 `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Recv_Invite_) Reset()                    { *m = Req_Recv_Invite_{} }
func (m *Req_Recv_Invite_) String() string            { return proto.CompactTextString(m) }
func (*Req_Recv_Invite_) ProtoMessage()               {}
func (*Req_Recv_Invite_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{33} }

func (m *Req_Recv_Invite_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

// 响应 领取邀请码奖励
type Resp_Recv_Invite_ struct {
	Uid              *int64          `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Rewards          []*Reward_Info_ `protobuf:"bytes,2,rep,name=Rewards" json:"Rewards,omitempty"`
	State            *int32          `protobuf:"varint,3,opt,name=State" json:"State,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Recv_Invite_) Reset()                    { *m = Resp_Recv_Invite_{} }
func (m *Resp_Recv_Invite_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Recv_Invite_) ProtoMessage()               {}
func (*Resp_Recv_Invite_) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{34} }

func (m *Resp_Recv_Invite_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Resp_Recv_Invite_) GetRewards() []*Reward_Info_ {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *Resp_Recv_Invite_) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func init() {
	proto.RegisterType((*Friend_Info_)(nil), "protocol.Friend_Info_")
	proto.RegisterType((*Req_Friend_Info_)(nil), "protocol.Req_Friend_Info_")
	proto.RegisterType((*Resp_Friend_Info_)(nil), "protocol.Resp_Friend_Info_")
	proto.RegisterType((*Req_Friend_Apply_)(nil), "protocol.Req_Friend_Apply_")
	proto.RegisterType((*Resp_Friend_Apply_)(nil), "protocol.Resp_Friend_Apply_")
	proto.RegisterType((*Req_Friend_ApplyRet_)(nil), "protocol.Req_Friend_ApplyRet_")
	proto.RegisterType((*Resp_Friend_ApplyRet_)(nil), "protocol.Resp_Friend_ApplyRet_")
	proto.RegisterType((*Req_Friend_Find_)(nil), "protocol.Req_Friend_Find_")
	proto.RegisterType((*Resp_Friend_Find_)(nil), "protocol.Resp_Friend_Find_")
	proto.RegisterType((*Resp_PlayerUpdate_Friend_)(nil), "protocol.Resp_PlayerUpdate_Friend_")
	proto.RegisterType((*Req_Friend_Del_)(nil), "protocol.Req_Friend_Del_")
	proto.RegisterType((*Resp_Friend_Del_)(nil), "protocol.Resp_Friend_Del_")
	proto.RegisterType((*Req_Friend_GiftSend_)(nil), "protocol.Req_Friend_GiftSend_")
	proto.RegisterType((*Resp_Friend_GiftSend_)(nil), "protocol.Resp_Friend_GiftSend_")
	proto.RegisterType((*Req_Friend_Recomm_)(nil), "protocol.Req_Friend_Recomm_")
	proto.RegisterType((*Resp_Friend_Recomm_)(nil), "protocol.Resp_Friend_Recomm_")
	proto.RegisterType((*Req_Friend_GiftRecv_)(nil), "protocol.Req_Friend_GiftRecv_")
	proto.RegisterType((*Resp_Friend_GiftRecv_)(nil), "protocol.Resp_Friend_GiftRecv_")
	proto.RegisterType((*Req_Chest_Help_)(nil), "protocol.Req_Chest_Help_")
	proto.RegisterType((*Resp_Chest_Help_)(nil), "protocol.Resp_Chest_Help_")
	proto.RegisterType((*Req_Share_)(nil), "protocol.Req_Share_")
	proto.RegisterType((*Resp_Share_)(nil), "protocol.Resp_Share_")
	proto.RegisterType((*Req_Click_Share_)(nil), "protocol.Req_Click_Share_")
	proto.RegisterType((*Resp_Click_Share_)(nil), "protocol.Resp_Click_Share_")
	proto.RegisterType((*Req_Watch_Adv_)(nil), "protocol.Req_Watch_Adv_")
	proto.RegisterType((*Resp_Watch_Adv_)(nil), "protocol.Resp_Watch_Adv_")
	proto.RegisterType((*Req_Share_GameInfo_)(nil), "protocol.Req_Share_GameInfo_")
	proto.RegisterType((*Resp_Share_GameInfo_)(nil), "protocol.Resp_Share_GameInfo_")
	proto.RegisterType((*Req_Get_Channel_Friends_)(nil), "protocol.Req_Get_Channel_Friends_")
	proto.RegisterType((*Resp_Get_Channel_Friends_)(nil), "protocol.Resp_Get_Channel_Friends_")
	proto.RegisterType((*Req_Set_Channel_Friends_)(nil), "protocol.Req_Set_Channel_Friends_")
	proto.RegisterType((*Req_Friend_Invite_Info_)(nil), "protocol.Req_Friend_Invite_Info_")
	proto.RegisterType((*Resp_Friend_Invite_Info_)(nil), "protocol.Resp_Friend_Invite_Info_")
	proto.RegisterType((*Req_Recv_Invite_)(nil), "protocol.Req_Recv_Invite_")
	proto.RegisterType((*Resp_Recv_Invite_)(nil), "protocol.Resp_Recv_Invite_")
}

func init() { proto.RegisterFile("friend.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 873 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0x96, 0xe3, 0xb8, 0x69, 0x26, 0xfd, 0xd3, 0xd6, 0x4d, 0xfb, 0xa7, 0xbd, 0x28, 0xd5, 0x8a,
	0x43, 0x25, 0x44, 0x24, 0x2a, 0xc4, 0x05, 0x02, 0x89, 0xd2, 0xa8, 0x69, 0x24, 0x5a, 0xa1, 0x1c,
	0x54, 0x2e, 0x90, 0x8c, 0xeb, 0x6c, 0x15, 0x0b, 0x27, 0x36, 0x8e, 0x1b, 0x9a, 0x77, 0xe1, 0x15,
	0x78, 0x02, 0x5e, 0x8e, 0x9d, 0xd9, 0xb5, 0x63, 0x27, 0x21, 0xad, 0x80, 0x9b, 0x44, 0x3b, 0x3b,
	0xc7, 0x6f, 0xbe, 0x99, 0x35, 0xac, 0x5d, 0x87, 0x2e, 0x1f, 0xf6, 0x6a, 0x41, 0xe8, 0x47, 0xbe,
	0xb9, 0x4a, 0x7f, 0x8e, 0xef, 0xed, 0xc1, 0x95, 0x3d, 0xe2, 0x52, 0xca, 0xde, 0xc2, 0xda, 0x29,
	0x69, 0x59, 0xcd, 0xe1, 0xb5, 0x6f, 0x99, 0x25, 0xd0, 0xbb, 0x6e, 0xaf, 0xaa, 0x1d, 0x68, 0x87,
	0xba, 0xb9, 0x01, 0xab, 0x0d, 0xf7, 0x3a, 0x6a, 0x8b, 0xeb, 0x6a, 0x4e, 0x48, 0x56, 0xcd, 0x4d,
	0x28, 0x92, 0x24, 0xb2, 0x23, 0x5e, 0xd5, 0x85, 0xc8, 0x60, 0x26, 0x6c, 0xb4, 0xf8, 0x57, 0x2b,
	0xed, 0x85, 0xfd, 0xd4, 0x60, 0xb3, 0xc5, 0x47, 0x41, 0x46, 0x6a, 0x6e, 0x41, 0x29, 0x76, 0x77,
	0x71, 0x33, 0xa0, 0x18, 0x86, 0xb9, 0x03, 0xe5, 0x94, 0xf0, 0xdc, 0xbe, 0xa5, 0x48, 0x46, 0xac,
	0xdc, 0xe2, 0xce, 0x18, 0x95, 0xf5, 0xb4, 0xb2, 0x12, 0xa2, 0x72, 0x9e, 0xe4, 0x8f, 0xc0, 0xc0,
	0x10, 0xa3, 0xaa, 0x71, 0xa0, 0x1f, 0x96, 0x8e, 0x76, 0x6a, 0x71, 0xad, 0xb5, 0x4c, 0x02, 0xeb,
	0x50, 0x38, 0x0e, 0x02, 0xcf, 0xe5, 0xa3, 0xea, 0x8a, 0x50, 0xd4, 0xcd, 0x4a, 0x5c, 0xbd, 0xf2,
	0x56, 0xa0, 0x8a, 0x8e, 0x31, 0xf9, 0xa4, 0x22, 0xb4, 0x98, 0x58, 0x66, 0x19, 0x56, 0xda, 0xa1,
	0x33, 0xc5, 0x46, 0x9c, 0xeb, 0x9c, 0xce, 0x39, 0x3a, 0xaf, 0x41, 0xbe, 0x33, 0x09, 0x62, 0x50,
	0xde, 0x81, 0x99, 0xae, 0xff, 0x8f, 0x7c, 0x74, 0xa0, 0x32, 0x9b, 0x46, 0x8b, 0x47, 0xf3, 0x5e,
	0x44, 0x55, 0xe2, 0x7c, 0x61, 0x0f, 0x38, 0xb9, 0x29, 0xa6, 0xdc, 0xea, 0xa4, 0x20, 0x7a, 0x2a,
	0x0c, 0x25, 0x54, 0xac, 0x0b, 0xdb, 0x73, 0x99, 0xfd, 0x03, 0xb7, 0xcf, 0x32, 0x2c, 0x38, 0x75,
	0xc5, 0x0f, 0x96, 0x43, 0xe6, 0x1a, 0x99, 0x2b, 0x66, 0x51, 0xa5, 0xec, 0x55, 0x96, 0x1f, 0x52,
	0x3f, 0xe9, 0xa2, 0x36, 0xdb, 0xc5, 0x0f, 0x9e, 0x3d, 0xe1, 0xa1, 0x22, 0xd7, 0x0f, 0x0d, 0x76,
	0xc9, 0x58, 0x4a, 0xbb, 0x41, 0x4f, 0x90, 0x31, 0xf6, 0xb4, 0x98, 0x64, 0x33, 0x64, 0xca, 0x65,
	0x49, 0xa3, 0xdf, 0x97, 0x34, 0x79, 0x22, 0x4d, 0x0d, 0xca, 0x27, 0x7d, 0x7b, 0x38, 0xe4, 0x9e,
	0xd4, 0xbb, 0x83, 0x75, 0xec, 0x39, 0xac, 0xa7, 0xa0, 0xa9, 0x73, 0xef, 0x4e, 0x22, 0xb0, 0x23,
	0x44, 0x73, 0x0a, 0xcf, 0xbd, 0x6c, 0x5e, 0x66, 0xe8, 0x12, 0x63, 0xb0, 0xdc, 0x4e, 0x94, 0xc3,
	0x5e, 0x64, 0x09, 0x31, 0x35, 0xcc, 0xac, 0x82, 0xd9, 0x68, 0x15, 0x24, 0x78, 0x12, 0x4d, 0x00,
	0xeb, 0x0f, 0x06, 0x16, 0xfb, 0x0c, 0x5b, 0x69, 0x5f, 0x4a, 0x8c, 0xc6, 0xdd, 0x11, 0x0f, 0x9b,
	0x75, 0xea, 0xac, 0x9e, 0x10, 0x03, 0x13, 0x20, 0x5e, 0x35, 0x1d, 0x7f, 0x28, 0x6e, 0xb1, 0x11,
	0x06, 0x02, 0x8e, 0xe7, 0x6e, 0xe8, 0x11, 0xe0, 0x45, 0x13, 0x20, 0xf7, 0x7e, 0x4c, 0x20, 0x1b,
	0xec, 0xf1, 0x5c, 0x95, 0xd8, 0xd4, 0xb9, 0x10, 0xec, 0xcd, 0x7c, 0x55, 0x52, 0xf1, 0x21, 0xe4,
	0xb1, 0x2d, 0xf3, 0x1c, 0xcb, 0xf4, 0x6c, 0x5f, 0xf6, 0xec, 0xa4, 0xcf, 0x47, 0x91, 0x75, 0xc6,
	0xbd, 0x80, 0xe0, 0x68, 0xf6, 0x6e, 0x25, 0xa1, 0xd8, 0x27, 0xd5, 0xa0, 0xb4, 0x82, 0xd8, 0x8d,
	0x1d, 0x77, 0x20, 0xce, 0x7c, 0x10, 0x28, 0xd4, 0x94, 0x8d, 0xe4, 0xdb, 0x21, 0x14, 0x49, 0x9d,
	0xc2, 0xe3, 0x08, 0x95, 0x8e, 0xb6, 0xa7, 0xe1, 0xa5, 0x27, 0x19, 0x7d, 0x0f, 0x00, 0xa3, 0xb7,
	0xfb, 0x76, 0xc8, 0xad, 0x64, 0x2b, 0xc8, 0xc8, 0x97, 0x50, 0xa2, 0xc8, 0x8b, 0x2e, 0xb3, 0x29,
	0xc8, 0x9d, 0xf2, 0x04, 0x0a, 0x2d, 0xfe, 0xcd, 0x0e, 0x7b, 0x0b, 0x78, 0x2e, 0x2f, 0x54, 0xd0,
	0x86, 0x9c, 0xe0, 0x13, 0xcf, 0x75, 0xbe, 0xc4, 0xde, 0x17, 0x94, 0x34, 0x05, 0x3a, 0x17, 0xbf,
	0x11, 0x64, 0xd2, 0xa5, 0xfe, 0x21, 0x35, 0xce, 0xd4, 0x6c, 0xff, 0xbd, 0xa7, 0x7d, 0x28, 0x63,
	0x4a, 0x97, 0x76, 0xe4, 0xf4, 0xad, 0xe3, 0xde, 0x78, 0x16, 0x8b, 0x33, 0xec, 0x92, 0x88, 0x94,
	0x52, 0x48, 0x95, 0xab, 0x2d, 0x2b, 0x37, 0xf1, 0x44, 0xbd, 0x61, 0xdb, 0x48, 0xdc, 0x18, 0xf1,
	0x86, 0xe0, 0xa6, 0xc4, 0xc4, 0x47, 0xb6, 0x25, 0x60, 0x27, 0x72, 0x34, 0x6e, 0x47, 0x3c, 0x50,
	0xa8, 0xff, 0x07, 0x46, 0xdb, 0xf1, 0x43, 0xc9, 0x67, 0x43, 0xa4, 0x50, 0xec, 0xd8, 0x57, 0x1e,
	0x4f, 0xf5, 0xb9, 0x32, 0x4d, 0x22, 0xb9, 0x22, 0x4c, 0x4e, 0xed, 0x81, 0xeb, 0x4d, 0x9a, 0x75,
	0xb9, 0x5b, 0x0c, 0xf6, 0x1a, 0xaa, 0x98, 0x47, 0x43, 0x2c, 0x64, 0xb5, 0x63, 0x14, 0x83, 0x47,
	0x72, 0x11, 0x39, 0x8e, 0x7f, 0x33, 0x8c, 0xa8, 0xb4, 0x22, 0x0a, 0x94, 0x92, 0xaa, 0xc2, 0x55,
	0x8b, 0x71, 0xa1, 0xb9, 0x40, 0x26, 0xde, 0x57, 0xda, 0x9d, 0x0b, 0x4f, 0xc5, 0x91, 0x03, 0x2a,
	0x06, 0x50, 0x3c, 0x8e, 0xc2, 0x61, 0x10, 0xf1, 0x50, 0x0e, 0x29, 0x7b, 0x2a, 0x13, 0x6d, 0xdf,
	0x27, 0x51, 0xb6, 0x0b, 0xff, 0x67, 0x3e, 0x11, 0xc6, 0xae, 0x58, 0xd8, 0x12, 0xe1, 0xef, 0x1a,
	0x3a, 0x4a, 0x7f, 0x29, 0x4c, 0x2f, 0x91, 0x21, 0x62, 0x68, 0xf1, 0x61, 0x96, 0x40, 0xcb, 0x45,
	0x20, 0x51, 0x8e, 0x77, 0x88, 0x4e, 0x29, 0x62, 0x0b, 0xe8, 0x9b, 0x84, 0x60, 0x8c, 0x57, 0x97,
	0x41, 0xdb, 0x46, 0xc0, 0x7c, 0x3e, 0x91, 0x7e, 0x43, 0xf1, 0xee, 0xcf, 0x0c, 0x45, 0x61, 0xe9,
	0x50, 0x3c, 0x90, 0x43, 0x41, 0xab, 0x43, 0xa5, 0x96, 0xd9, 0x8b, 0xec, 0xa3, 0x22, 0xfb, 0x6f,
	0x35, 0xd2, 0xb1, 0x72, 0x4b, 0x19, 0x99, 0xd4, 0x40, 0xcf, 0xff, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd4, 0xbd, 0xaf, 0xbf, 0xbe, 0x09, 0x00, 0x00,
}
