// Code generated by protoc-gen-go.
// source: mail.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Mail_Info_ struct {
	ID               *int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Title            *string `protobuf:"bytes,2,opt,name=Title" json:"Title,omitempty"`
	Content          *string `protobuf:"bytes,3,opt,name=Content" json:"Content,omitempty"`
	Gift             *bool   `protobuf:"varint,4,opt,name=Gift" json:"Gift,omitempty"`
	Status           *int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	SendTime         *int64  `protobuf:"varint,6,opt,name=SendTime" json:"SendTime,omitempty"`
	Type             *int32  `protobuf:"varint,7,opt,name=Type" json:"Type,omitempty"`
	SrcName          *string `protobuf:"bytes,8,opt,name=SrcName" json:"SrcName,omitempty"`
	ExpiryTime       *int64  `protobuf:"varint,9,opt,name=ExpiryTime" json:"ExpiryTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Mail_Info_) Reset()                    { *m = Mail_Info_{} }
func (m *Mail_Info_) String() string            { return proto.CompactTextString(m) }
func (*Mail_Info_) ProtoMessage()               {}
func (*Mail_Info_) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *Mail_Info_) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Mail_Info_) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Mail_Info_) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Mail_Info_) GetGift() bool {
	if m != nil && m.Gift != nil {
		return *m.Gift
	}
	return false
}

func (m *Mail_Info_) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *Mail_Info_) GetSendTime() int64 {
	if m != nil && m.SendTime != nil {
		return *m.SendTime
	}
	return 0
}

func (m *Mail_Info_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Mail_Info_) GetSrcName() string {
	if m != nil && m.SrcName != nil {
		return *m.SrcName
	}
	return ""
}

func (m *Mail_Info_) GetExpiryTime() int64 {
	if m != nil && m.ExpiryTime != nil {
		return *m.ExpiryTime
	}
	return 0
}

type Req_Mail_List_ struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Mail_List_) Reset()                    { *m = Req_Mail_List_{} }
func (m *Req_Mail_List_) String() string            { return proto.CompactTextString(m) }
func (*Req_Mail_List_) ProtoMessage()               {}
func (*Req_Mail_List_) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

type Resp_Mail_List_ struct {
	MailInfos        []*Mail_Info_ `protobuf:"bytes,1,rep,name=MailInfos" json:"MailInfos,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Resp_Mail_List_) Reset()                    { *m = Resp_Mail_List_{} }
func (m *Resp_Mail_List_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Mail_List_) ProtoMessage()               {}
func (*Resp_Mail_List_) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *Resp_Mail_List_) GetMailInfos() []*Mail_Info_ {
	if m != nil {
		return m.MailInfos
	}
	return nil
}

// 请求 邮件读取
type Req_Mail_Read_ struct {
	MailID           *int64 `protobuf:"varint,1,opt,name=MailID" json:"MailID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Req_Mail_Read_) Reset()                    { *m = Req_Mail_Read_{} }
func (m *Req_Mail_Read_) String() string            { return proto.CompactTextString(m) }
func (*Req_Mail_Read_) ProtoMessage()               {}
func (*Req_Mail_Read_) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{3} }

func (m *Req_Mail_Read_) GetMailID() int64 {
	if m != nil && m.MailID != nil {
		return *m.MailID
	}
	return 0
}

// 响应 邮件读取
type Resp_Mail_Read_ struct {
	MailID           *int64          `protobuf:"varint,1,opt,name=MailID" json:"MailID,omitempty"`
	Content          *string         `protobuf:"bytes,2,opt,name=Content" json:"Content,omitempty"`
	Reward           []*Reward_Info_ `protobuf:"bytes,3,rep,name=Reward" json:"Reward,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Mail_Read_) Reset()                    { *m = Resp_Mail_Read_{} }
func (m *Resp_Mail_Read_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Mail_Read_) ProtoMessage()               {}
func (*Resp_Mail_Read_) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{4} }

func (m *Resp_Mail_Read_) GetMailID() int64 {
	if m != nil && m.MailID != nil {
		return *m.MailID
	}
	return 0
}

func (m *Resp_Mail_Read_) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Resp_Mail_Read_) GetReward() []*Reward_Info_ {
	if m != nil {
		return m.Reward
	}
	return nil
}

// 请求 邮件领取
type Req_Mail_Receive_ struct {
	MailID           []int64 `protobuf:"varint,1,rep,name=MailID" json:"MailID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Mail_Receive_) Reset()                    { *m = Req_Mail_Receive_{} }
func (m *Req_Mail_Receive_) String() string            { return proto.CompactTextString(m) }
func (*Req_Mail_Receive_) ProtoMessage()               {}
func (*Req_Mail_Receive_) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{5} }

func (m *Req_Mail_Receive_) GetMailID() []int64 {
	if m != nil {
		return m.MailID
	}
	return nil
}

// 响应 邮件领取
type Resp_Mail_Receive_ struct {
	Status           *int32          `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
	Reward           []*Reward_Info_ `protobuf:"bytes,2,rep,name=Reward" json:"Reward,omitempty"`
	ChestRewards     []*Reward_Info_ `protobuf:"bytes,3,rep,name=ChestRewards" json:"ChestRewards,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Resp_Mail_Receive_) Reset()                    { *m = Resp_Mail_Receive_{} }
func (m *Resp_Mail_Receive_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Mail_Receive_) ProtoMessage()               {}
func (*Resp_Mail_Receive_) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{6} }

func (m *Resp_Mail_Receive_) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *Resp_Mail_Receive_) GetReward() []*Reward_Info_ {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *Resp_Mail_Receive_) GetChestRewards() []*Reward_Info_ {
	if m != nil {
		return m.ChestRewards
	}
	return nil
}

// 请求 邮件删除
type Req_Mail_Delete_ struct {
	MailID           []int64 `protobuf:"varint,1,rep,name=MailID" json:"MailID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Mail_Delete_) Reset()                    { *m = Req_Mail_Delete_{} }
func (m *Req_Mail_Delete_) String() string            { return proto.CompactTextString(m) }
func (*Req_Mail_Delete_) ProtoMessage()               {}
func (*Req_Mail_Delete_) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{7} }

func (m *Req_Mail_Delete_) GetMailID() []int64 {
	if m != nil {
		return m.MailID
	}
	return nil
}

type Push_Mail_ struct {
	MailInfos        []*Mail_Info_ `protobuf:"bytes,1,rep,name=MailInfos" json:"MailInfos,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Push_Mail_) Reset()                    { *m = Push_Mail_{} }
func (m *Push_Mail_) String() string            { return proto.CompactTextString(m) }
func (*Push_Mail_) ProtoMessage()               {}
func (*Push_Mail_) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{8} }

func (m *Push_Mail_) GetMailInfos() []*Mail_Info_ {
	if m != nil {
		return m.MailInfos
	}
	return nil
}

// game server 请求发送邮件
type Req_Send_Mail_ struct {
	SrcUid           *int64  `protobuf:"varint,1,opt,name=SrcUid" json:"SrcUid,omitempty"`
	DescUid          *string `protobuf:"bytes,2,opt,name=DescUid" json:"DescUid,omitempty"`
	Title            *string `protobuf:"bytes,3,opt,name=Title" json:"Title,omitempty"`
	Content          *string `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
	Gift             *string `protobuf:"bytes,5,opt,name=Gift" json:"Gift,omitempty"`
	ExpiryTime       *int64  `protobuf:"varint,6,opt,name=ExpiryTime" json:"ExpiryTime,omitempty"`
	Type             *int32  `protobuf:"varint,7,opt,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Send_Mail_) Reset()                    { *m = Req_Send_Mail_{} }
func (m *Req_Send_Mail_) String() string            { return proto.CompactTextString(m) }
func (*Req_Send_Mail_) ProtoMessage()               {}
func (*Req_Send_Mail_) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{9} }

func (m *Req_Send_Mail_) GetSrcUid() int64 {
	if m != nil && m.SrcUid != nil {
		return *m.SrcUid
	}
	return 0
}

func (m *Req_Send_Mail_) GetDescUid() string {
	if m != nil && m.DescUid != nil {
		return *m.DescUid
	}
	return ""
}

func (m *Req_Send_Mail_) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Req_Send_Mail_) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Req_Send_Mail_) GetGift() string {
	if m != nil && m.Gift != nil {
		return *m.Gift
	}
	return ""
}

func (m *Req_Send_Mail_) GetExpiryTime() int64 {
	if m != nil && m.ExpiryTime != nil {
		return *m.ExpiryTime
	}
	return 0
}

func (m *Req_Send_Mail_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*Mail_Info_)(nil), "protocol.Mail_Info_")
	proto.RegisterType((*Req_Mail_List_)(nil), "protocol.Req_Mail_List_")
	proto.RegisterType((*Resp_Mail_List_)(nil), "protocol.Resp_Mail_List_")
	proto.RegisterType((*Req_Mail_Read_)(nil), "protocol.Req_Mail_Read_")
	proto.RegisterType((*Resp_Mail_Read_)(nil), "protocol.Resp_Mail_Read_")
	proto.RegisterType((*Req_Mail_Receive_)(nil), "protocol.Req_Mail_Receive_")
	proto.RegisterType((*Resp_Mail_Receive_)(nil), "protocol.Resp_Mail_Receive_")
	proto.RegisterType((*Req_Mail_Delete_)(nil), "protocol.Req_Mail_Delete_")
	proto.RegisterType((*Push_Mail_)(nil), "protocol.Push_Mail_")
	proto.RegisterType((*Req_Send_Mail_)(nil), "protocol.Req_Send_Mail_")
}

func init() { proto.RegisterFile("mail.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0x25, 0x4d, 0xd3, 0xa6, 0xf7, 0xf5, 0xb5, 0x7d, 0xc3, 0xe3, 0x11, 0xde, 0xaa, 0x44, 0xd0,
	0x2e, 0xa4, 0x0b, 0xc1, 0x8d, 0xdb, 0x56, 0xa4, 0xa0, 0x22, 0x69, 0xdd, 0xb8, 0x09, 0x31, 0xb9,
	0xa5, 0x03, 0x69, 0x12, 0x33, 0x53, 0xb5, 0xee, 0xfc, 0x1d, 0xfe, 0x59, 0xe7, 0x23, 0x36, 0xa9,
	0x04, 0x75, 0x35, 0xdc, 0x3b, 0xf7, 0x9e, 0x73, 0xee, 0xe1, 0x00, 0xac, 0x03, 0x1a, 0x8f, 0xb3,
	0x3c, 0xe5, 0x29, 0xb1, 0xd5, 0x13, 0xa6, 0xf1, 0x7f, 0xb8, 0x0f, 0x18, 0xea, 0xae, 0xfb, 0x66,
	0x00, 0x5c, 0x89, 0x21, 0x7f, 0x96, 0x2c, 0x53, 0x9f, 0x00, 0x34, 0x66, 0x53, 0xc7, 0x18, 0x1a,
	0x23, 0x93, 0xfc, 0x06, 0x6b, 0x41, 0x79, 0x8c, 0x4e, 0x43, 0x94, 0x1d, 0xd2, 0x87, 0xf6, 0x24,
	0x4d, 0x38, 0x26, 0xdc, 0x31, 0x55, 0xa3, 0x0b, 0xcd, 0x0b, 0xba, 0xe4, 0x4e, 0x53, 0x54, 0x36,
	0xe9, 0x41, 0x6b, 0xce, 0x03, 0xbe, 0x61, 0x8e, 0x25, 0x6a, 0x8b, 0x0c, 0xc0, 0x9e, 0x63, 0x12,
	0x2d, 0xe8, 0x1a, 0x9d, 0x96, 0xc2, 0x13, 0xf3, 0x8b, 0x6d, 0x86, 0x4e, 0x5b, 0xfd, 0x0b, 0xb8,
	0x79, 0x1e, 0x5e, 0x07, 0xe2, 0xdb, 0x56, 0x70, 0x82, 0xfb, 0xfc, 0x39, 0xa3, 0xf9, 0x56, 0xad,
	0x74, 0xe4, 0x8a, 0x3b, 0x80, 0x9e, 0x87, 0x0f, 0xbe, 0x12, 0x78, 0x49, 0x19, 0xf7, 0xdd, 0x33,
	0xe8, 0x7b, 0xc8, 0xb2, 0x4a, 0x8b, 0x1c, 0x41, 0x47, 0x56, 0xf2, 0x00, 0x26, 0xa4, 0x9b, 0xa3,
	0x5f, 0x27, 0x7f, 0xc7, 0x1f, 0xc7, 0x8e, 0xcb, 0xe3, 0xdc, 0x61, 0x05, 0xcd, 0xc3, 0x20, 0xf2,
	0xa5, 0x68, 0xb5, 0x5a, 0x9c, 0xec, 0xde, 0x55, 0xd1, 0x6b, 0x47, 0xaa, 0x36, 0x68, 0x5f, 0x0e,
	0xa1, 0xe5, 0xe1, 0x53, 0x90, 0x47, 0xc2, 0x16, 0xc9, 0xfd, 0xaf, 0xe4, 0xd6, 0xfd, 0x82, 0xfd,
	0x00, 0xfe, 0x54, 0xd8, 0x43, 0xa4, 0x8f, 0xb8, 0x8f, 0x6e, 0x0a, 0x01, 0x2f, 0x40, 0xaa, 0x02,
	0xca, 0xa9, 0xc2, 0x5b, 0x43, 0x79, 0x57, 0x52, 0x36, 0xbe, 0xa2, 0x24, 0xc7, 0xd0, 0x9d, 0xac,
	0x90, 0x71, 0xdd, 0x64, 0xdf, 0x08, 0x74, 0x61, 0xb0, 0x13, 0x38, 0xc5, 0x18, 0x79, 0x8d, 0xbe,
	0x53, 0x80, 0x9b, 0x0d, 0x5b, 0xe9, 0xa1, 0x9f, 0x3b, 0xff, 0x6a, 0x68, 0xeb, 0x65, 0x22, 0x8a,
	0x5d, 0x79, 0x53, 0x1e, 0xde, 0xd2, 0xa8, 0xf4, 0x75, 0x8a, 0x4c, 0x35, 0xb4, 0xaf, 0xbb, 0xf8,
	0x99, 0x9f, 0xe3, 0xd7, 0xdc, 0x8b, 0x9f, 0x55, 0x93, 0x9e, 0x9a, 0xc0, 0xbd, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x58, 0xa6, 0x4b, 0x41, 0x0c, 0x03, 0x00, 0x00,
}
