// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 请求 创建新用户
type Req_Create_User_ struct {
	Account          *string `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Create_User_) Reset()                    { *m = Req_Create_User_{} }
func (m *Req_Create_User_) String() string            { return proto.CompactTextString(m) }
func (*Req_Create_User_) ProtoMessage()               {}
func (*Req_Create_User_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *Req_Create_User_) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

// 响应 创建新用户
type Resp_Create_User_ struct {
	Account          *string `protobuf:"bytes,2,opt,name=Account" json:"Account,omitempty"`
	UserID           *int64  `protobuf:"varint,3,opt,name=UserID" json:"UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_Create_User_) Reset()                    { *m = Resp_Create_User_{} }
func (m *Resp_Create_User_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Create_User_) ProtoMessage()               {}
func (*Resp_Create_User_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

func (m *Resp_Create_User_) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *Resp_Create_User_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 请求 更新邮件列表
type Req_Mail_Update_ struct {
	UserID           *int64  `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	MailID           []int64 `protobuf:"varint,2,rep,name=MailID" json:"MailID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Req_Mail_Update_) Reset()                    { *m = Req_Mail_Update_{} }
func (m *Req_Mail_Update_) String() string            { return proto.CompactTextString(m) }
func (*Req_Mail_Update_) ProtoMessage()               {}
func (*Req_Mail_Update_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

func (m *Req_Mail_Update_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Req_Mail_Update_) GetMailID() []int64 {
	if m != nil {
		return m.MailID
	}
	return nil
}

// 响应 更新邮件列表
type Resp_Mail_Update_ struct {
	UserID           *int64  `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
	MailID           []int64 `protobuf:"varint,2,rep,name=MailID" json:"MailID,omitempty"`
	Status           []int32 `protobuf:"varint,3,rep,name=Status" json:"Status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_Mail_Update_) Reset()                    { *m = Resp_Mail_Update_{} }
func (m *Resp_Mail_Update_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Mail_Update_) ProtoMessage()               {}
func (*Resp_Mail_Update_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

func (m *Resp_Mail_Update_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Mail_Update_) GetMailID() []int64 {
	if m != nil {
		return m.MailID
	}
	return nil
}

func (m *Resp_Mail_Update_) GetStatus() []int32 {
	if m != nil {
		return m.Status
	}
	return nil
}

// 新邮件推送
type Resp_NewMail_Push_ struct {
	MailID           *int64  `protobuf:"varint,1,opt,name=MailID" json:"MailID,omitempty"`
	UserIDs          []int64 `protobuf:"varint,2,rep,name=UserIDs" json:"UserIDs,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_NewMail_Push_) Reset()                    { *m = Resp_NewMail_Push_{} }
func (m *Resp_NewMail_Push_) String() string            { return proto.CompactTextString(m) }
func (*Resp_NewMail_Push_) ProtoMessage()               {}
func (*Resp_NewMail_Push_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{4} }

func (m *Resp_NewMail_Push_) GetMailID() int64 {
	if m != nil && m.MailID != nil {
		return *m.MailID
	}
	return 0
}

func (m *Resp_NewMail_Push_) GetUserIDs() []int64 {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

// 测试协议
type Resp_Test_Func_ struct {
	Type             *int32 `protobuf:"varint,1,opt,name=Type" json:"Type,omitempty"`
	UserID           *int64 `protobuf:"varint,2,opt,name=UserID" json:"UserID,omitempty"`
	Exp              *int32 `protobuf:"varint,3,opt,name=Exp" json:"Exp,omitempty"`
	Fid              *int32 `protobuf:"varint,4,opt,name=Fid" json:"Fid,omitempty"`
	Prob             *int32 `protobuf:"varint,5,opt,name=Prob" json:"Prob,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Resp_Test_Func_) Reset()                    { *m = Resp_Test_Func_{} }
func (m *Resp_Test_Func_) String() string            { return proto.CompactTextString(m) }
func (*Resp_Test_Func_) ProtoMessage()               {}
func (*Resp_Test_Func_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{5} }

func (m *Resp_Test_Func_) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Resp_Test_Func_) GetUserID() int64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *Resp_Test_Func_) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Resp_Test_Func_) GetFid() int32 {
	if m != nil && m.Fid != nil {
		return *m.Fid
	}
	return 0
}

func (m *Resp_Test_Func_) GetProb() int32 {
	if m != nil && m.Prob != nil {
		return *m.Prob
	}
	return 0
}

// 快速通关
type Resp_LazyPass_ struct {
	Uid              *int64  `protobuf:"varint,1,opt,name=Uid" json:"Uid,omitempty"`
	Cid              []int32 `protobuf:"varint,2,rep,name=Cid" json:"Cid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Resp_LazyPass_) Reset()                    { *m = Resp_LazyPass_{} }
func (m *Resp_LazyPass_) String() string            { return proto.CompactTextString(m) }
func (*Resp_LazyPass_) ProtoMessage()               {}
func (*Resp_LazyPass_) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{6} }

func (m *Resp_LazyPass_) GetUid() int64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Resp_LazyPass_) GetCid() []int32 {
	if m != nil {
		return m.Cid
	}
	return nil
}

func init() {
	proto.RegisterType((*Req_Create_User_)(nil), "protocol.Req_Create_User_")
	proto.RegisterType((*Resp_Create_User_)(nil), "protocol.Resp_Create_User_")
	proto.RegisterType((*Req_Mail_Update_)(nil), "protocol.Req_Mail_Update_")
	proto.RegisterType((*Resp_Mail_Update_)(nil), "protocol.Resp_Mail_Update_")
	proto.RegisterType((*Resp_NewMail_Push_)(nil), "protocol.Resp_NewMail_Push_")
	proto.RegisterType((*Resp_Test_Func_)(nil), "protocol.Resp_Test_Func_")
	proto.RegisterType((*Resp_LazyPass_)(nil), "protocol.Resp_LazyPass_")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x8f, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x86, 0xd9, 0x4d, 0xe3, 0xc7, 0x58, 0x5a, 0xcd, 0x69, 0x8f, 0x25, 0x5e, 0x8a, 0x07, 0x0f,
	0xa2, 0x3f, 0x40, 0x56, 0x0b, 0x82, 0xca, 0x52, 0xbb, 0x78, 0x0c, 0x71, 0x1b, 0xb0, 0x50, 0x9a,
	0x98, 0x64, 0xd5, 0xfa, 0xeb, 0xcd, 0xcc, 0x56, 0xd8, 0x8b, 0x87, 0x9e, 0xc2, 0xc3, 0xbc, 0xef,
	0x33, 0x13, 0x18, 0x06, 0xe3, 0x3f, 0x8d, 0xbf, 0x74, 0xde, 0x46, 0x2b, 0x8e, 0xe8, 0x69, 0xec,
	0x5a, 0x9e, 0xc3, 0xe9, 0xdc, 0x7c, 0xa8, 0xd2, 0x1b, 0x1d, 0x8d, 0xaa, 0x53, 0x4a, 0x89, 0x31,
	0x1c, 0xde, 0x36, 0x8d, 0x6d, 0x37, 0xb1, 0xc8, 0x26, 0xd9, 0xf4, 0x58, 0x5e, 0xc3, 0xd9, 0xdc,
	0x04, 0xf7, 0x6f, 0x2a, 0xc7, 0x94, 0x18, 0xc1, 0x01, 0x4e, 0x1e, 0xee, 0x0a, 0x96, 0x98, 0xc9,
	0xab, 0x4e, 0xfd, 0xa4, 0x57, 0x6b, 0x55, 0xbb, 0x25, 0x36, 0x7b, 0x19, 0x34, 0x33, 0x64, 0x9c,
	0x27, 0xce, 0x27, 0x2c, 0x75, 0xca, 0xdd, 0xa6, 0x7d, 0x4a, 0xc8, 0x2f, 0x51, 0xc7, 0x36, 0xa4,
	0xc5, 0x6c, 0xca, 0xe5, 0x0d, 0x08, 0x92, 0x3c, 0x9b, 0x2f, 0xf2, 0x54, 0x6d, 0x78, 0x57, 0xbd,
	0x56, 0x67, 0x49, 0xf7, 0x77, 0xd6, 0xb0, 0xdb, 0xfd, 0x0a, 0x63, 0xaa, 0x2d, 0x4c, 0x88, 0x6a,
	0xd6, 0x6e, 0x1a, 0x25, 0x86, 0x30, 0x58, 0x6c, 0x9d, 0xa1, 0x06, 0xef, 0xdd, 0x91, 0x93, 0xe1,
	0x04, 0xd8, 0xfd, 0xb7, 0xa3, 0xdf, 0x72, 0x84, 0xd9, 0x6a, 0x59, 0x0c, 0x08, 0x52, 0xaf, 0xf2,
	0xf6, 0xad, 0xe0, 0x48, 0xf2, 0x02, 0x46, 0x24, 0x7e, 0xd4, 0x3f, 0xdb, 0x4a, 0x87, 0xa0, 0x30,
	0x5c, 0xa7, 0x70, 0xf6, 0xa7, 0x29, 0x13, 0xe0, 0x11, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0x1e,
	0x70, 0x5c, 0xe4, 0xa8, 0x01, 0x00, 0x00,
}
